"""this file is auto-generated by rhinocode stubmaker. do not make changes"""

# region: Exports
__all__ = ["GH_PivotAction", "GH_LayoutAction", "GH_NickNameAction", "GH_LockedAction", "GH_HiddenAction", "GH_IconDisplayAction", "GH_IconOverrideAction", "GH_DataMatchingAction", "GH_DataModificationAction", "GH_WireDisplayAction", "GH_WireAction", "GH_AddObjectAction", "GH_RemoveObjectAction", "GH_GenericObjectAction", "GH_PersistentDataAction", "GH_AddStateAction", "GH_RemoveStateAction"]
# endregion

# region: Imports
from GH_IO import Serialization
from Grasshopper import Kernel
from Grasshopper.Kernel import Undo
from System.Runtime import CompilerServices
from typing import overload
# endregion

# region: Grasshopper, Version=8.19.25132.1001

class GH_PivotAction(Undo.GH_ObjectUndoAction):
    """Records a single object pivot event. Useful for tracking object movement.

    """
    def __init__(self, obj: Kernel.IGH_DocumentObject): ...

class GH_LayoutAction(Undo.GH_ObjectUndoAction):
    """Records a single object layout event. Useful for tracking object resizes.

    """
    def __init__(self, obj: Kernel.IGH_DocumentObject): ...

class GH_NickNameAction(Undo.GH_ObjectUndoAction):
    """Records a single object NickName and IconDisplayMode event.

    """
    def __init__(self, obj: Kernel.IGH_DocumentObject): ...

class GH_LockedAction(Undo.GH_ObjectUndoAction):
    """Records a single object Enabled event.

    """
    def __init__(self, obj: Kernel.IGH_ActiveObject): ...
    @property
    def ExpiresSolution(self) -> bool: ...

class GH_HiddenAction(Undo.GH_ObjectUndoAction):
    """Records a single object Preview event.

    """
    def __init__(self, obj: Kernel.IGH_ActiveObject): ...
    @property
    def ExpiresDisplay(self) -> bool: ...

class GH_IconDisplayAction(Undo.GH_ObjectUndoAction):
    """Records a single icon display mode event.

    """
    def __init__(self, obj: Kernel.IGH_DocumentObject): ...

class GH_IconOverrideAction(Undo.GH_ObjectUndoAction):
    """Records a single icon override event.

    """
    def __init__(self, obj: Kernel.IGH_DocumentObject): ...

class GH_DataMatchingAction(Undo.GH_ObjectUndoAction):
    """Records a single Component DataComparison event.

    """
    def __init__(self, obj: Kernel.IGH_Component): ...
    @property
    def ExpiresSolution(self) -> bool: ...

class GH_DataModificationAction(Undo.GH_ObjectUndoAction):
    """Records a single Parameter DataModification event.

    """
    def __init__(self, obj: Kernel.IGH_Param): ...
    @property
    def ExpiresSolution(self) -> bool: ...

class GH_WireDisplayAction(Undo.GH_ObjectUndoAction):
    """Records a single wire display mode event.

    """
    def __init__(self, obj: Kernel.IGH_Param): ...

class GH_WireAction(Undo.GH_UndoAction):
    """Records any change to the input wires of a given parameter.

    """
    def __init__(self, param: Kernel.IGH_Param): ...
    @property
    def ExpiresSolution(self) -> bool: ...

class GH_AddObjectAction(Undo.GH_UndoAction):
    """Records a single object addition.

    """
    def __init__(self, obj: Kernel.IGH_DocumentObject): ...
    @property
    def ExpiresSolution(self) -> bool: ...

class GH_RemoveObjectAction(Undo.GH_ArchivedUndoAction):
    """Records a single object removal.

    """
    def __init__(self, obj: Kernel.IGH_DocumentObject): ...
    @property
    def ExpiresSolution(self) -> bool: ...

class GH_GenericObjectAction(Undo.GH_ArchivedUndoAction):
    """Records a single object change. Object changes are undone/redone by (de)serializing the objects. Object changes also keep track of all wires feeding into and coming out of the object.

    """
    def __init__(self, obj: Kernel.IGH_DocumentObject): ...
    @property
    def ExpiresSolution(self) -> bool: ...

class GH_PersistentDataAction(Undo.GH_ObjectUndoAction):
    """Records the changes in the persistent data of a parameter.

    GH_PersistentDataAction[T]
    """
    def __init__(self, obj: Kernel.GH_PersistentParam): ...
    @property
    def ExpiresSolution(self) -> bool: ...

class GH_AddStateAction(Undo.GH_ArchivedUndoAction):
    """Record the addition of a single solution state to a document.

    """
    def __init__(self, index: int, state: Kernel.GH_State): ...
    @overload
    def Read(self, reader: Serialization.GH_IReader) -> bool: ...
    @overload
    def Write(self, writer: Serialization.GH_IWriter) -> bool: ...

class GH_RemoveStateAction(Undo.GH_ArchivedUndoAction):
    """Record the removal of a single solution state from a document.

    """
    def __init__(self, index: int, state: Kernel.GH_State): ...
    @overload
    def Read(self, reader: Serialization.GH_IReader) -> bool: ...
    @overload
    def Write(self, writer: Serialization.GH_IWriter) -> bool: ...

# endregion
