"""this file is auto-generated by rhinocode stubmaker. do not make changes"""

# region: Exports
__all__ = ["SystemDrawingSection"]
# endregion

# region: Imports
from System import Configuration
from System.Runtime import CompilerServices
from typing import overload
import System
# endregion

# region: System.Configuration.ConfigurationManager, Version=7.0.0.0

class SystemDrawingSection(Configuration.ConfigurationSection):
    """    """
    def __init__(self): ...
    @property
    def BitmapSuffix(self) -> str: ...
    @BitmapSuffix.setter
    def BitmapSuffix(self, value: System.Void): ...

# endregion
