"""this file is auto-generated by rhinocode stubmaker. do not make changes"""

# region: Exports
__all__ = ["ProjectCommand_00000000"]
# endregion

# region: Imports
from Rhino import Commands
from System.Runtime import CompilerServices
from typing import overload
import System
# endregion

# region: RhinoCodePlatform.Rhino3D, Version=8.19.25132.1001

class ProjectCommand_00000000(Commands.Command):
    """    """
    def __init__(self): ...
    @property
    def CommandId(self) -> System.Guid: ...
    @property
    def EnglishName(self) -> str: ...
    @property
    def Instance(self) -> ProjectCommand_00000000: ...

# endregion
