"""this file is auto-generated by rhinocode stubmaker. do not make changes"""

# region: Exports
__all__ = ["WindowStyle", "RhinoCore"]
# endregion

# region: Imports
from System.Runtime import CompilerServices
from typing import overload
import enum
import System
# endregion

# region: RhinoCommon, Version=8.19.25132.1001

class WindowStyle(enum.Enum):
    Normal = 0
    Hidden = 1
    Minimized = 2
    Maximized = 3
    NoWindow = -1

class RhinoCore(object):
    """Represents an instance of RhinoCore.DLL.

    """
    @overload
    def __init__(self): ...
    @overload
    def __init__(self, args: System.System.Array[str]): ...
    @overload
    def __init__(self, args: System.System.Array[str], windowStyle: WindowStyle): ...
    @overload
    def __init__(self, args: System.System.Array[str], windowStyle: WindowStyle, hostWnd: System.IntPtr): ...
    @overload
    def Dispose() -> None: ...
    @overload
    def DoEvents() -> bool: ...
    @overload
    def DoIdle() -> bool: ...
    @overload
    def InvokeInHostContext(self, action: System.Action) -> None: ...
    @overload
    def InvokeInHostContext(self, func: System.Func) -> T: ...
    @overload
    def RaiseIdle() -> None: ...
    @overload
    def Run() -> int: ...

# endregion
