"""this file is auto-generated by rhinocode stubmaker. do not make changes"""

# region: Exports
__all__ = ["ExceptionDispatchInfo", "FirstChanceExceptionEventArgs"]
# endregion

# region: Imports
from System.Runtime import CompilerServices
from typing import overload
import System
# endregion

# region: System.Private.CoreLib, Version=7.0.0.0

class ExceptionDispatchInfo(object):
    """    """
    @overload
    @staticmethod
    def Capture(source: System.Exception) -> ExceptionDispatchInfo: ...
    @property
    def SourceException(self) -> System.Exception: ...
    @overload
    @staticmethod
    def SetCurrentStackTrace(source: System.Exception) -> System.Exception: ...
    @overload
    @staticmethod
    def SetRemoteStackTrace(source: System.Exception, stackTrace: str) -> System.Exception: ...
    @overload
    def Throw() -> None: ...
    @overload
    @staticmethod
    def Throw(source: System.Exception) -> None: ...

class FirstChanceExceptionEventArgs(System.EventArgs):
    """    """
    def __init__(self, exception: System.Exception): ...
    @property
    def Exception(self) -> System.Exception: ...

# endregion
