"""this file is auto-generated by rhinocode stubmaker. do not make changes"""

# region: Exports
__all__ = ["ProviderBase", "ProviderCollection", "ProviderException"]
# endregion

# region: Imports
from System import Collections
from System.Collections import Specialized
from System.Runtime import CompilerServices
from typing import overload
import System
# endregion

# region: System.Configuration.ConfigurationManager, Version=7.0.0.0

class ProviderBase(object):
    """    """
    @property
    def Description(self) -> str: ...
    @property
    def Name(self) -> str: ...
    @overload
    def Initialize(self, name: str, config: Specialized.NameValueCollection) -> None: ...

class ProviderCollection(object):
    """    """
    def __init__(self): ...
    @overload
    def Add(self, provider: ProviderBase) -> None: ...
    @overload
    def Clear() -> None: ...
    @overload
    def CopyTo(self, array: System.Array[ProviderBase], index: int) -> None: ...
    @property
    def Count(self) -> int: ...
    @property
    def IsSynchronized(self) -> bool: ...
    @property
    def Item(self) -> ProviderBase: ...
    @property
    def SyncRoot(self) -> object: ...
    @overload
    def GetEnumerator() -> Collections.IEnumerator: ...
    @overload
    def Remove(self, name: str) -> None: ...
    @overload
    def SetReadOnly() -> None: ...

class ProviderException(System.Exception):
    """    """
    @overload
    def __init__(self): ...
    @overload
    def __init__(self, message: str): ...
    @overload
    def __init__(self, message: str, innerException: System.Exception): ...

# endregion
