"""this file is auto-generated by rhinocode stubmaker. do not make changes"""

# region: Exports
__all__ = ["GH_PointGetter", "GH_LineGetter", "GH_ArcGetter", "GH_CircleGetter", "GH_RectangleGetter", "GH_BoxGetter", "GH_PlaneGetter", "GH_CurveGetter", "GH_SurfaceGetter", "GH_BrepGetter", "GH_ExtrusionGetter", "GH_SubDGetter", "GH_MeshGetter", "GH_PointCloudGetter", "GH_InstanceReferenceGetter", "GH_HatchGetter", "GH_TextDotGetter", "GH_TextEntityGetter", "GH_LeaderGetter", "GH_AngularDimensionGetter", "GH_CentermarkGetter", "GH_LinearDimensionGetter", "GH_OrdinateDimensionGetter", "GH_RadialDimensionGetter", "GH_LightGetter", "GH_GeometryGetter", "GH_VectorGetter", "GH_TransformGetter"]
# endregion

# region: Imports
from Grasshopper import Kernel
from Grasshopper.Kernel import Types
from Rhino import Geometry
from System.Collections import Generic
from System.Runtime import CompilerServices
from typing import overload
import System
# endregion

# region: Grasshopper, Version=8.19.25132.1001

class GH_PointGetter(object):
    """    """
    def __init__(self): ...
    @overload
    def DefaultRefType() -> Types.GH_PointRefType: ...
    @property
    def AcceptPreselected(self) -> bool: ...
    @property
    def PointRefType(self) -> Types.GH_PointRefType: ...
    @overload
    def GetPoint() -> Types.GH_Point: ...
    @overload
    def GetPoint(self, base: Geometry.Point3d) -> Types.GH_Point: ...
    @overload
    @staticmethod
    def GetPoint(prompt: str, basePoint: Geometry.Point3d) -> (Kernel.GH_GetterResult, Geometry.Point3d): ...
    @overload
    def GetPoints() -> Generic.List: ...
    @overload
    def RecreateSetup(self, pt: Types.GH_Point) -> None: ...
    @AcceptPreselected.setter
    def AcceptPreselected(self, value: System.Void): ...
    @PointRefType.setter
    def PointRefType(self, value: System.Void): ...

class GH_LineGetter(object):
    """    """
    @overload
    @staticmethod
    def GetLine() -> Types.GH_Line: ...
    @overload
    @staticmethod
    def GetLines() -> Generic.List: ...

class GH_ArcGetter(object):
    """    """
    @overload
    @staticmethod
    def GetArc() -> Types.GH_Arc: ...
    @overload
    @staticmethod
    def GetArcs() -> Generic.List: ...

class GH_CircleGetter(object):
    """    """
    @overload
    @staticmethod
    def GetCircle() -> Types.GH_Circle: ...
    @overload
    @staticmethod
    def GetCircles() -> Generic.List: ...

class GH_RectangleGetter(object):
    """    """
    @overload
    @staticmethod
    def GetRectangle() -> Types.GH_Rectangle: ...
    @overload
    @staticmethod
    def GetRectangles() -> Generic.List: ...

class GH_BoxGetter(object):
    """    """
    @overload
    @staticmethod
    def GetBox() -> Types.GH_Box: ...
    @overload
    @staticmethod
    def GetBoxes() -> Generic.List: ...

class GH_PlaneGetter(object):
    """    """
    @overload
    @staticmethod
    def GetPlane() -> Types.GH_Plane: ...
    @overload
    @staticmethod
    def GetPlanes() -> Generic.List: ...
    @overload
    @staticmethod
    def RotatePlaneX(plane: Geometry.Plane, pt: Geometry.Point3d) -> Geometry.Plane: ...
    @overload
    @staticmethod
    def RotatePlaneY(plane: Geometry.Plane, pt: Geometry.Point3d) -> Geometry.Plane: ...

class GH_CurveGetter(object):
    """    """
    @overload
    @staticmethod
    def GetCurve() -> Types.GH_Curve: ...
    @overload
    @staticmethod
    def GetCurves() -> Generic.List: ...

class GH_SurfaceGetter(object):
    """    """
    @overload
    @staticmethod
    def GetSurface() -> Types.GH_Surface: ...
    @overload
    @staticmethod
    def GetSurfaces() -> Generic.List: ...

class GH_BrepGetter(object):
    """    """
    @overload
    @staticmethod
    def GetBrep() -> Types.GH_Brep: ...
    @overload
    @staticmethod
    def GetBreps() -> Generic.List: ...

class GH_ExtrusionGetter(object):
    """    """
    @overload
    @staticmethod
    def GetExtrusion() -> Types.GH_Extrusion: ...
    @overload
    @staticmethod
    def GetExtrusions() -> Generic.List: ...

class GH_SubDGetter(object):
    """    """
    @overload
    @staticmethod
    def GetSubD() -> Types.GH_SubD: ...
    @overload
    @staticmethod
    def GetSubDs() -> Generic.List: ...

class GH_MeshGetter(object):
    """    """
    @overload
    @staticmethod
    def GetMesh() -> Types.GH_Mesh: ...
    @overload
    @staticmethod
    def GetMeshes() -> Generic.List: ...

class GH_PointCloudGetter(object):
    """    """
    @overload
    @staticmethod
    def GetPointCloud() -> Types.GH_PointCloud: ...
    @overload
    @staticmethod
    def GetPointClouds() -> Generic.List: ...

class GH_InstanceReferenceGetter(object):
    """    """
    @overload
    @staticmethod
    def GetInstanceReference() -> Types.GH_InstanceReference: ...
    @overload
    @staticmethod
    def GetInstanceReferences() -> Generic.List: ...

class GH_HatchGetter(object):
    """    """
    @overload
    @staticmethod
    def GetHatch() -> Types.GH_Hatch: ...
    @overload
    @staticmethod
    def GetHatches() -> Generic.List: ...

class GH_TextDotGetter(object):
    """    """
    @overload
    @staticmethod
    def GetTextDot() -> Types.GH_TextDot: ...
    @overload
    @staticmethod
    def GetTextDots() -> Generic.List: ...

class GH_TextEntityGetter(object):
    """    """
    @overload
    @staticmethod
    def GetTextEntities() -> Generic.List: ...
    @overload
    @staticmethod
    def GetTextEntity() -> Types.GH_TextEntity: ...

class GH_LeaderGetter(object):
    """    """
    @overload
    @staticmethod
    def GetLeader() -> Types.GH_Leader: ...
    @overload
    @staticmethod
    def GetLeaders() -> Generic.List: ...

class GH_AngularDimensionGetter(object):
    """    """
    @overload
    @staticmethod
    def GetAngularDimension() -> Types.GH_AngularDimension: ...
    @overload
    @staticmethod
    def GetAngularDimensions() -> Generic.List: ...

class GH_CentermarkGetter(object):
    """    """
    @overload
    @staticmethod
    def GetCentermark() -> Types.GH_Centermark: ...
    @overload
    @staticmethod
    def GetCentermarks() -> Generic.List: ...

class GH_LinearDimensionGetter(object):
    """    """
    @overload
    @staticmethod
    def GetLinearDimension() -> Types.GH_LinearDimension: ...
    @overload
    @staticmethod
    def GetLinearDimensions() -> Generic.List: ...

class GH_OrdinateDimensionGetter(object):
    """    """
    @overload
    @staticmethod
    def GetOrdinateDimension() -> Types.GH_OrdinateDimension: ...
    @overload
    @staticmethod
    def GetOrdinateDimensions() -> Generic.List: ...

class GH_RadialDimensionGetter(object):
    """    """
    @overload
    @staticmethod
    def GetRadialDimension() -> Types.GH_RadialDimension: ...
    @overload
    @staticmethod
    def GetRadialDimensions() -> Generic.List: ...

class GH_LightGetter(object):
    """    """
    @overload
    @staticmethod
    def GetLight() -> Types.GH_Light: ...
    @overload
    @staticmethod
    def GetLights() -> Generic.List: ...

class GH_GeometryGetter(object):
    """    """
    @overload
    @staticmethod
    def GetGeometries() -> Generic.List: ...
    @overload
    @staticmethod
    def GetGeometry() -> Types.IGH_GeometricGoo: ...

class GH_VectorGetter(object):
    """    """
    @overload
    @staticmethod
    def GetVector() -> Types.GH_Vector: ...
    @overload
    @staticmethod
    def GetVectors() -> Generic.List: ...

class GH_TransformGetter(object):
    """    """

# endregion
