"""this file is auto-generated by rhinocode stubmaker. do not make changes"""

# region: Exports
__all__ = ["WorldMapDayNight"]
# endregion

# region: Imports
from Rhino import Geometry
from System import Drawing
from System.Runtime import CompilerServices
from typing import overload
import System
# endregion

# region: RhinoCommon, Version=8.19.25132.1001

class WorldMapDayNight(object):
    """    """
    def __init__(self): ...
    @overload
    def Dispose() -> None: ...
    @overload
    def HasMapForCurrentSettings() -> bool: ...
    @overload
    def LocationToMap(self, latlong: Geometry.Point2d) -> Drawing.Point: ...
    @overload
    def MakeMapBitmap() -> None: ...
    @overload
    def Map() -> Drawing.Image: ...
    @overload
    def MapToLocation(self, mapPoint: Drawing.Point) -> Geometry.Point2d: ...
    @overload
    def SetDayNightDisplay(self, bOn: bool) -> None: ...
    @overload
    def SetEnabled(self, bEnabled: bool) -> None: ...
    @overload
    def SetTimeInfo(self, dt: System.DateTime, timezone: float, daylightSavingMinutes: int, bDaylightSavingsOn: bool) -> None: ...

# endregion
