"""this file is auto-generated by rhinocode stubmaker. do not make changes"""

# region: Exports
__all__ = ["McNeelPython2IterExtension", "McNeelPython2LenExtension"]
# endregion

# region: Imports
from System.Runtime import CompilerServices
from typing import overload
# endregion

# region: RhinoCodePlatform.Rhino3D, Version=8.19.25132.1001

class McNeelPython2IterExtension(object):
    """    """

class McNeelPython2LenExtension(object):
    """    """

# endregion
