"""this file is auto-generated by rhinocode stubmaker. do not make changes"""

# region: Exports
__all__ = ["ComBinder", "ComMethodDesc", "ComParamDesc", "ComType", "ComTypeClassDesc", "ComTypeDesc", "ComTypeEnumDesc", "ComTypeLibDesc", "ComTypeLibInfo", "ComTypeLibMemberDesc"]
# endregion

# region: Imports
from System import Dynamic
from System.Collections import Generic
from System.Linq import Expressions
from System.Runtime import CompilerServices
from typing import overload
import enum
import System
# endregion

# region: Microsoft.Dynamic, Version=1.3.1.0

class ComBinder(object):
    """    """
    @overload
    @staticmethod
    def CanComBind(value: object) -> bool: ...
    @overload
    @staticmethod
    def GetDynamicMemberNames(value: object) -> Generic.IEnumerable: ...
    @overload
    @staticmethod
    def IsComObject(value: object) -> bool: ...
    @overload
    @staticmethod
    def TryBindGetIndex(binder: Dynamic.GetIndexBinder, instance: Dynamic.DynamicMetaObject, args: Dynamic.System.Array[Dynamic.DynamicMetaObject]) -> (bool, Dynamic.DynamicMetaObject): ...
    @overload
    @staticmethod
    def TryBindGetMember(binder: Dynamic.GetMemberBinder, instance: Dynamic.DynamicMetaObject) -> (bool, Dynamic.DynamicMetaObject): ...
    @overload
    @staticmethod
    def TryBindGetMember(binder: Dynamic.GetMemberBinder, instance: Dynamic.DynamicMetaObject, delayInvocation: bool) -> (bool, Dynamic.DynamicMetaObject): ...
    @overload
    @staticmethod
    def TryBindInvoke(binder: Dynamic.InvokeBinder, instance: Dynamic.DynamicMetaObject, args: Dynamic.System.Array[Dynamic.DynamicMetaObject]) -> (bool, Dynamic.DynamicMetaObject): ...
    @overload
    @staticmethod
    def TryBindInvokeMember(binder: Dynamic.InvokeMemberBinder, instance: Dynamic.DynamicMetaObject, args: Dynamic.System.Array[Dynamic.DynamicMetaObject]) -> (bool, Dynamic.DynamicMetaObject): ...
    @overload
    @staticmethod
    def TryBindSetIndex(binder: Dynamic.SetIndexBinder, instance: Dynamic.DynamicMetaObject, args: Dynamic.System.Array[Dynamic.DynamicMetaObject], value: Dynamic.DynamicMetaObject) -> (bool, Dynamic.DynamicMetaObject): ...
    @overload
    @staticmethod
    def TryBindSetMember(binder: Dynamic.SetMemberBinder, instance: Dynamic.DynamicMetaObject, value: Dynamic.DynamicMetaObject) -> (bool, Dynamic.DynamicMetaObject): ...
    @overload
    @staticmethod
    def TryConvert(binder: Dynamic.ConvertBinder, instance: Dynamic.DynamicMetaObject) -> (bool, Dynamic.DynamicMetaObject): ...

class ComMethodDesc(object):
    """    """
    @property
    def DispId(self) -> int: ...
    @property
    def IsDataMember(self) -> bool: ...
    @property
    def IsPropertyGet(self) -> bool: ...
    @property
    def IsPropertyPut(self) -> bool: ...
    @property
    def IsPropertyPutRef(self) -> bool: ...
    @property
    def Name(self) -> str: ...

class ComParamDesc(object):
    """    """
    @property
    def ByReference(self) -> bool: ...
    @property
    def IsArray(self) -> bool: ...
    @property
    def IsOptional(self) -> bool: ...
    @property
    def IsOut(self) -> bool: ...
    @property
    def ParameterType(self) -> System.Type: ...
    @overload
    def ToString() -> str: ...

class ComType(enum.Enum):
    Class = 0
    Enum = 1
    Interface = 2

class ComTypeClassDesc(ComTypeDesc):
    """    """
    @overload
    def CreateInstance() -> object: ...
    @overload
    def GetMetaObject(self, parameter: Expressions.Expression) -> Dynamic.DynamicMetaObject: ...

class ComTypeDesc(ComTypeLibMemberDesc):
    """    """
    @property
    def TypeLib(self) -> ComTypeLibDesc: ...
    @property
    def TypeName(self) -> str: ...

class ComTypeEnumDesc(ComTypeDesc):
    """    """
    @overload
    def GetMemberNames() -> System.System.Array[str]: ...
    @overload
    def GetValue(self, enumValueName: str) -> object: ...
    @overload
    def ToString() -> str: ...

class ComTypeLibDesc(object):
    """    """
    @overload
    @staticmethod
    def CreateFromGuid(typeLibGuid: System.Guid) -> ComTypeLibInfo: ...
    @overload
    @staticmethod
    def CreateFromObject(rcw: object) -> ComTypeLibInfo: ...
    @property
    def Documentation(self) -> str: ...
    @property
    def Guid(self) -> System.Guid: ...
    @property
    def Name(self) -> str: ...
    @property
    def VersionMajor(self) -> System.Int16: ...
    @property
    def VersionMinor(self) -> System.Int16: ...
    @overload
    def GetMemberNames() -> System.System.Array[str]: ...
    @overload
    def GetTypeLibObjectDesc(self, member: str) -> object: ...
    @overload
    def ToString() -> str: ...

class ComTypeLibInfo(object):
    """    """
    @property
    def Guid(self) -> System.Guid: ...
    @property
    def Name(self) -> str: ...
    @property
    def TypeLibDesc(self) -> ComTypeLibDesc: ...
    @property
    def VersionMajor(self) -> System.Int16: ...
    @property
    def VersionMinor(self) -> System.Int16: ...
    @overload
    def GetMemberNames() -> System.System.Array[str]: ...

class ComTypeLibMemberDesc(object):
    """    """
    @property
    def Kind(self) -> ComType: ...

# endregion
