"""this file is auto-generated by rhinocode stubmaker. do not make changes"""

# region: Exports
__all__ = ["CreaseEdges", "RefinementSettings", "LoopFormula"]
# endregion

# region: Imports
from System import Threading
from System.Runtime import CompilerServices
from typing import overload
import enum
import System
# endregion

# region: RhinoCommon, Version=8.19.25132.1001

class CreaseEdges(enum.Enum):
    NakedFixed = 0
    NakedSmooth = 1
    CornerFixedOtherCreased = 2
    Auto = 3

class RefinementSettings(object):
    """Defines the way a mesh refinement modifier works.

    """
    def __init__(self): ...
    @property
    def ContinueRequest(self) -> Threading.CancellationToken: ...
    @property
    def HasPull(self) -> bool: ...
    @property
    def Level(self) -> int: ...
    @property
    def NakedEdgeMode(self) -> CreaseEdges: ...
    @ContinueRequest.setter
    def ContinueRequest(self, value: System.Void): ...
    @Level.setter
    def Level(self, value: System.Void): ...
    @NakedEdgeMode.setter
    def NakedEdgeMode(self, value: System.Void): ...

class LoopFormula(enum.Enum):
    Loop = 0
    Warren = 1
    WarrenWeimer = 2

# endregion
