"""this file is auto-generated by rhinocode stubmaker. do not make changes"""

# region: Exports
__all__ = ["ContextValue"]
# endregion

# region: Imports
from System.Runtime import CompilerServices
from typing import overload
import System
# endregion

# region: Microsoft.VisualBasic.Forms, Version=7.0.0.0

class ContextValue(object):
    """    ContextValue[T]
    """
    def __init__(self): ...
    @property
    def Value(self) -> T: ...
    @Value.setter
    def Value(self, value: System.Void): ...

# endregion
