"""this file is auto-generated by rhinocode stubmaker. do not make changes"""

# region: Exports
__all__ = []
# endregion

# region: Imports
from System.Runtime import CompilerServices
from typing import overload
# endregion

# region: Exports
__all__ = []
# endregion

# region: Imports
from System.Runtime import CompilerServices
from typing import overload
# endregion

# region: System.Private.CoreLib, Version=7.0.0.0

# endregion

# region: System.Security.Permissions, Version=7.0.0.0

# endregion
