"""this file is auto-generated by rhinocode stubmaker. do not make changes"""

# region: Exports
__all__ = ["AuthorizationContext", "EvaluationContext", "IAuthorizationComponent", "IAuthorizationPolicy"]
# endregion

# region: Imports
from System.Collections import Generic
from System.Collections import ObjectModel
from System.IdentityModel import Claims
from System.Runtime import CompilerServices
from typing import overload
import System
# endregion

# region: System.Private.ServiceModel, Version=4.9.0.0

class AuthorizationContext(object):
    """    """
    @overload
    @staticmethod
    def CreateDefaultAuthorizationContext(authorizationPolicies: Generic.IList) -> AuthorizationContext: ...
    @property
    def ClaimSets(self) -> ObjectModel.ReadOnlyCollection: ...
    @property
    def ExpirationTime(self) -> System.DateTime: ...
    @property
    def Id(self) -> str: ...
    @property
    def Properties(self) -> Generic.IDictionary: ...

class EvaluationContext(object):
    """    """
    @overload
    def AddClaimSet(self, policy: IAuthorizationPolicy, claimSet: Claims.ClaimSet) -> None: ...
    @property
    def ClaimSets(self) -> ObjectModel.ReadOnlyCollection: ...
    @property
    def Generation(self) -> int: ...
    @property
    def Properties(self) -> Generic.IDictionary: ...
    @overload
    def RecordExpirationTime(self, expirationTime: System.DateTime) -> None: ...

class IAuthorizationComponent:
    """    """
    @property
    def Id(self) -> str: ...

class IAuthorizationPolicy:
    """    """
    @overload
    def Evaluate(self, evaluationContext: EvaluationContext) -> (bool, object): ...
    @property
    def Issuer(self) -> Claims.ClaimSet: ...

# endregion
