"""this file is auto-generated by rhinocode stubmaker. do not make changes"""

# region: Exports
__all__ = ["IApplicationIdentifier", "IFileChangeNotificationSystem", "IMemoryCacheManager"]
# endregion

# region: Imports
from System.Runtime import Caching
from System.Runtime import CompilerServices
from typing import overload
import System
# endregion

# region: System.Runtime.Caching, Version=4.0.0.0

class IApplicationIdentifier:
    """    """
    @overload
    def GetApplicationId() -> str: ...

class IFileChangeNotificationSystem:
    """    """
    @overload
    def StartMonitoring(self, filePath: str, onChangedCallback: Caching.OnChangedCallback) -> (object, System.DateTimeOffset, System.Int64): ...
    @overload
    def StopMonitoring(self, filePath: str, state: object) -> None: ...

class IMemoryCacheManager:
    """    """
    @overload
    def ReleaseCache(self, cache: Caching.MemoryCache) -> None: ...
    @overload
    def UpdateCacheSize(self, size: System.Int64, cache: Caching.MemoryCache) -> None: ...

# endregion
