"""this file is auto-generated by rhinocode stubmaker. do not make changes"""

# region: Exports
__all__ = []
# endregion

# region: Imports
from System.Runtime import CompilerServices
from typing import overload
# endregion

# region: Eto, Version=2.9.0.0

# endregion
