"""this file is auto-generated by rhinocode stubmaker. do not make changes"""

# region: Exports
__all__ = ["ComActivationContextInternal", "ComponentActivator", "ComponentEntryPoint", "ComActivator", "InMemoryAssemblyLoader"]
# endregion

# region: Imports
from System.Runtime import CompilerServices
from typing import overload
import System
# endregion

# region: System.Private.CoreLib, Version=7.0.0.0

class ComActivationContextInternal(System.ValueType):
    """    """
    @property
    def ClassId(self) -> System.Guid: ...
    @property
    def InterfaceId(self) -> System.Guid: ...
    @property
    def AssemblyPathBuffer(self) -> System.Char: ...
    @property
    def AssemblyNameBuffer(self) -> System.Char: ...
    @property
    def TypeNameBuffer(self) -> System.Char: ...
    @property
    def ClassFactoryDest(self) -> System.IntPtr: ...

class ComponentActivator(object):
    """    """
    @overload
    @staticmethod
    def GetFunctionPointer(typeNameNative: System.IntPtr, methodNameNative: System.IntPtr, delegateTypeNative: System.IntPtr, loadContext: System.IntPtr, reserved: System.IntPtr, functionHandle: System.IntPtr) -> int: ...
    @overload
    @staticmethod
    def LoadAssemblyAndGetFunctionPointer(assemblyPathNative: System.IntPtr, typeNameNative: System.IntPtr, methodNameNative: System.IntPtr, delegateTypeNative: System.IntPtr, reserved: System.IntPtr, functionHandle: System.IntPtr) -> int: ...

class ComponentEntryPoint(System.MulticastDelegate):
    """    """
    def __init__(self, object_: object, method: System.IntPtr): ...
    @overload
    def BeginInvoke(self, args: System.IntPtr, sizeBytes: int, callback: System.AsyncCallback, object_: object) -> System.IAsyncResult: ...
    @overload
    def EndInvoke(self, result: System.IAsyncResult) -> int: ...
    @overload
    def Invoke(self, args: System.IntPtr, sizeBytes: int) -> int: ...

class ComActivator(object):
    """    """

class InMemoryAssemblyLoader(object):
    """    """
    @overload
    @staticmethod
    def LoadInMemoryAssembly(moduleHandle: System.IntPtr, assemblyPath: System.IntPtr) -> None: ...
    @overload
    @staticmethod
    def LoadInMemoryAssemblyInContext(moduleHandle: System.IntPtr, assemblyPath: System.IntPtr, loadContext: System.IntPtr) -> None: ...

# endregion
