"""this file is auto-generated by rhinocode stubmaker. do not make changes"""

# region: Exports
__all__ = ["AuthenticatedStream", "CipherSuitesPolicy", "NegotiateAuthentication", "NegotiateAuthenticationClientOptions", "NegotiateAuthenticationServerOptions", "NegotiateAuthenticationStatusCode", "ProtectionLevel", "SslApplicationProtocol", "SslCertificateTrust", "SslClientAuthenticationOptions", "SslClientHelloInfo", "SslServerAuthenticationOptions", "EncryptionPolicy", "RemoteCertificateValidationCallback", "LocalCertificateSelectionCallback", "ServerCertificateSelectionCallback", "ServerOptionsSelectionCallback", "SslStream", "SslStreamCertificateContext", "NegotiateStream", "TlsCipherSuite"]
# endregion

# region: Imports
from System import Buffers
from System import IO
from System import Net
from System import Threading
from System.Collections import Generic
from System.Runtime import CompilerServices
from System.Security import Authentication
from System.Security import Principal
from System.Security.Authentication import ExtendedProtection
from System.Security.Cryptography import X509Certificates
from System.Threading import Tasks
from typing import overload
import enum
import System
# endregion

# region: Exports
__all__ = ["AuthenticationLevel", "SslPolicyErrors"]
# endregion

# region: Imports
from System.Runtime import CompilerServices
from typing import overload
import enum
# endregion

# region: System.Net.Primitives, Version=7.0.0.0

class AuthenticationLevel(enum.Enum):
    None_ = 0
    MutualAuthRequested = 1
    MutualAuthRequired = 2

class SslPolicyErrors(enum.Enum):
    None_ = 0
    RemoteCertificateNotAvailable = 1
    RemoteCertificateNameMismatch = 2
    RemoteCertificateChainErrors = 4

# endregion

# region: System.Net.Security, Version=7.0.0.0

class AuthenticatedStream(IO.Stream):
    """    """
    @overload
    def DisposeAsync() -> Tasks.ValueTask: ...
    @property
    def IsAuthenticated(self) -> bool: ...
    @property
    def IsEncrypted(self) -> bool: ...
    @property
    def IsMutuallyAuthenticated(self) -> bool: ...
    @property
    def IsServer(self) -> bool: ...
    @property
    def IsSigned(self) -> bool: ...
    @property
    def LeaveInnerStreamOpen(self) -> bool: ...

class CipherSuitesPolicy(object):
    """    """
    def __init__(self, allowedCipherSuites: Generic.IEnumerable): ...
    @property
    def AllowedCipherSuites(self) -> Generic.IEnumerable: ...

class NegotiateAuthentication(object):
    """    """
    @overload
    def __init__(self, clientOptions: NegotiateAuthenticationClientOptions): ...
    @overload
    def __init__(self, serverOptions: NegotiateAuthenticationServerOptions): ...
    @overload
    def Dispose() -> None: ...
    @property
    def ImpersonationLevel(self) -> Principal.TokenImpersonationLevel: ...
    @property
    def IsAuthenticated(self) -> bool: ...
    @property
    def IsEncrypted(self) -> bool: ...
    @property
    def IsMutuallyAuthenticated(self) -> bool: ...
    @property
    def IsServer(self) -> bool: ...
    @property
    def IsSigned(self) -> bool: ...
    @property
    def Package(self) -> str: ...
    @property
    def ProtectionLevel(self) -> ProtectionLevel: ...
    @property
    def RemoteIdentity(self) -> Principal.IIdentity: ...
    @property
    def TargetName(self) -> str: ...
    @overload
    def GetOutgoingBlob(self, incomingBlob: System.ReadOnlySpan) -> (System.System.Array[System.Byte], NegotiateAuthenticationStatusCode): ...
    @overload
    def GetOutgoingBlob(self, incomingBlob: str) -> (str, NegotiateAuthenticationStatusCode): ...
    @overload
    def Unwrap(self, input_: System.ReadOnlySpan, outputWriter: Buffers.IBufferWriter) -> (NegotiateAuthenticationStatusCode, bool): ...
    @overload
    def UnwrapInPlace(self, input_: System.Span) -> (NegotiateAuthenticationStatusCode, int, int, bool): ...
    @overload
    def Wrap(self, input_: System.ReadOnlySpan, outputWriter: Buffers.IBufferWriter, requestEncryption: bool) -> (NegotiateAuthenticationStatusCode, bool): ...

class NegotiateAuthenticationClientOptions(object):
    """    """
    def __init__(self): ...
    @property
    def AllowedImpersonationLevel(self) -> Principal.TokenImpersonationLevel: ...
    @property
    def Binding(self) -> ExtendedProtection.ChannelBinding: ...
    @property
    def Credential(self) -> Net.NetworkCredential: ...
    @property
    def Package(self) -> str: ...
    @property
    def RequiredProtectionLevel(self) -> ProtectionLevel: ...
    @property
    def RequireMutualAuthentication(self) -> bool: ...
    @property
    def TargetName(self) -> str: ...
    @AllowedImpersonationLevel.setter
    def AllowedImpersonationLevel(self, value: System.Void): ...
    @Binding.setter
    def Binding(self, value: System.Void): ...
    @Credential.setter
    def Credential(self, value: System.Void): ...
    @Package.setter
    def Package(self, value: System.Void): ...
    @RequiredProtectionLevel.setter
    def RequiredProtectionLevel(self, value: System.Void): ...
    @RequireMutualAuthentication.setter
    def RequireMutualAuthentication(self, value: System.Void): ...
    @TargetName.setter
    def TargetName(self, value: System.Void): ...

class NegotiateAuthenticationServerOptions(object):
    """    """
    def __init__(self): ...
    @property
    def Binding(self) -> ExtendedProtection.ChannelBinding: ...
    @property
    def Credential(self) -> Net.NetworkCredential: ...
    @property
    def Package(self) -> str: ...
    @property
    def Policy(self) -> ExtendedProtection.ExtendedProtectionPolicy: ...
    @property
    def RequiredImpersonationLevel(self) -> Principal.TokenImpersonationLevel: ...
    @property
    def RequiredProtectionLevel(self) -> ProtectionLevel: ...
    @Binding.setter
    def Binding(self, value: System.Void): ...
    @Credential.setter
    def Credential(self, value: System.Void): ...
    @Package.setter
    def Package(self, value: System.Void): ...
    @Policy.setter
    def Policy(self, value: System.Void): ...
    @RequiredImpersonationLevel.setter
    def RequiredImpersonationLevel(self, value: System.Void): ...
    @RequiredProtectionLevel.setter
    def RequiredProtectionLevel(self, value: System.Void): ...

class NegotiateAuthenticationStatusCode(enum.Enum):
    Completed = 0
    ContinueNeeded = 1
    GenericFailure = 2
    BadBinding = 3
    Unsupported = 4
    MessageAltered = 5
    ContextExpired = 6
    CredentialsExpired = 7
    InvalidCredentials = 8
    InvalidToken = 9
    UnknownCredentials = 10
    QopNotSupported = 11
    OutOfSequence = 12
    SecurityQosFailed = 13
    TargetUnknown = 14
    ImpersonationValidationFailed = 15

class ProtectionLevel(enum.Enum):
    None_ = 0
    Sign = 1
    EncryptAndSign = 2

class SslApplicationProtocol(System.ValueType):
    """    """
    @overload
    def __init__(self, protocol: System.System.Array[System.Byte]): ...
    @overload
    def __init__(self, protocol: str): ...
    @property
    def Http3(self) -> SslApplicationProtocol: ...
    @property
    def Http2(self) -> SslApplicationProtocol: ...
    @property
    def Http11(self) -> SslApplicationProtocol: ...
    @overload
    def Equals(self, other: SslApplicationProtocol) -> bool: ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    @property
    def Protocol(self) -> System.ReadOnlyMemory: ...
    @overload
    def GetHashCode() -> int: ...
    @overload
    def ToString() -> str: ...

class SslCertificateTrust(object):
    """    """
    @overload
    @staticmethod
    def CreateForX509Collection(trustList: X509Certificates.X509Certificate2Collection, sendTrustInHandshake: bool) -> SslCertificateTrust: ...
    @overload
    @staticmethod
    def CreateForX509Store(store: X509Certificates.X509Store, sendTrustInHandshake: bool) -> SslCertificateTrust: ...

class SslClientAuthenticationOptions(object):
    """    """
    def __init__(self): ...
    @property
    def AllowRenegotiation(self) -> bool: ...
    @property
    def ApplicationProtocols(self) -> Generic.List: ...
    @property
    def CertificateChainPolicy(self) -> X509Certificates.X509ChainPolicy: ...
    @property
    def CertificateRevocationCheckMode(self) -> X509Certificates.X509RevocationMode: ...
    @property
    def CipherSuitesPolicy(self) -> CipherSuitesPolicy: ...
    @property
    def ClientCertificates(self) -> X509Certificates.X509CertificateCollection: ...
    @property
    def EnabledSslProtocols(self) -> Authentication.SslProtocols: ...
    @property
    def EncryptionPolicy(self) -> EncryptionPolicy: ...
    @property
    def LocalCertificateSelectionCallback(self) -> LocalCertificateSelectionCallback: ...
    @property
    def RemoteCertificateValidationCallback(self) -> RemoteCertificateValidationCallback: ...
    @property
    def TargetHost(self) -> str: ...
    @AllowRenegotiation.setter
    def AllowRenegotiation(self, value: System.Void): ...
    @ApplicationProtocols.setter
    def ApplicationProtocols(self, value: System.Void): ...
    @CertificateChainPolicy.setter
    def CertificateChainPolicy(self, value: System.Void): ...
    @CertificateRevocationCheckMode.setter
    def CertificateRevocationCheckMode(self, value: System.Void): ...
    @CipherSuitesPolicy.setter
    def CipherSuitesPolicy(self, value: System.Void): ...
    @ClientCertificates.setter
    def ClientCertificates(self, value: System.Void): ...
    @EnabledSslProtocols.setter
    def EnabledSslProtocols(self, value: System.Void): ...
    @EncryptionPolicy.setter
    def EncryptionPolicy(self, value: System.Void): ...
    @LocalCertificateSelectionCallback.setter
    def LocalCertificateSelectionCallback(self, value: System.Void): ...
    @RemoteCertificateValidationCallback.setter
    def RemoteCertificateValidationCallback(self, value: System.Void): ...
    @TargetHost.setter
    def TargetHost(self, value: System.Void): ...

class SslClientHelloInfo(System.ValueType):
    """    """
    def __init__(self, serverName: str, sslProtocols: Authentication.SslProtocols): ...
    @property
    def ServerName(self) -> str: ...
    @property
    def SslProtocols(self) -> Authentication.SslProtocols: ...

class SslServerAuthenticationOptions(object):
    """    """
    def __init__(self): ...
    @property
    def AllowRenegotiation(self) -> bool: ...
    @property
    def ApplicationProtocols(self) -> Generic.List: ...
    @property
    def CertificateChainPolicy(self) -> X509Certificates.X509ChainPolicy: ...
    @property
    def CertificateRevocationCheckMode(self) -> X509Certificates.X509RevocationMode: ...
    @property
    def CipherSuitesPolicy(self) -> CipherSuitesPolicy: ...
    @property
    def ClientCertificateRequired(self) -> bool: ...
    @property
    def EnabledSslProtocols(self) -> Authentication.SslProtocols: ...
    @property
    def EncryptionPolicy(self) -> EncryptionPolicy: ...
    @property
    def RemoteCertificateValidationCallback(self) -> RemoteCertificateValidationCallback: ...
    @property
    def ServerCertificate(self) -> X509Certificates.X509Certificate: ...
    @property
    def ServerCertificateContext(self) -> SslStreamCertificateContext: ...
    @property
    def ServerCertificateSelectionCallback(self) -> ServerCertificateSelectionCallback: ...
    @AllowRenegotiation.setter
    def AllowRenegotiation(self, value: System.Void): ...
    @ApplicationProtocols.setter
    def ApplicationProtocols(self, value: System.Void): ...
    @CertificateChainPolicy.setter
    def CertificateChainPolicy(self, value: System.Void): ...
    @CertificateRevocationCheckMode.setter
    def CertificateRevocationCheckMode(self, value: System.Void): ...
    @CipherSuitesPolicy.setter
    def CipherSuitesPolicy(self, value: System.Void): ...
    @ClientCertificateRequired.setter
    def ClientCertificateRequired(self, value: System.Void): ...
    @EnabledSslProtocols.setter
    def EnabledSslProtocols(self, value: System.Void): ...
    @EncryptionPolicy.setter
    def EncryptionPolicy(self, value: System.Void): ...
    @RemoteCertificateValidationCallback.setter
    def RemoteCertificateValidationCallback(self, value: System.Void): ...
    @ServerCertificate.setter
    def ServerCertificate(self, value: System.Void): ...
    @ServerCertificateContext.setter
    def ServerCertificateContext(self, value: System.Void): ...
    @ServerCertificateSelectionCallback.setter
    def ServerCertificateSelectionCallback(self, value: System.Void): ...

class EncryptionPolicy(enum.Enum):
    RequireEncryption = 0
    AllowNoEncryption = 1
    NoEncryption = 2

class RemoteCertificateValidationCallback(System.MulticastDelegate):
    """    """
    def __init__(self, object_: object, method: System.IntPtr): ...
    @overload
    def BeginInvoke(self, sender: object, certificate: X509Certificates.X509Certificate, chain: X509Certificates.X509Chain, sslPolicyErrors: SslPolicyErrors, callback: System.AsyncCallback, object_: object) -> System.IAsyncResult: ...
    @overload
    def EndInvoke(self, result: System.IAsyncResult) -> bool: ...
    @overload
    def Invoke(self, sender: object, certificate: X509Certificates.X509Certificate, chain: X509Certificates.X509Chain, sslPolicyErrors: SslPolicyErrors) -> bool: ...

class LocalCertificateSelectionCallback(System.MulticastDelegate):
    """    """
    def __init__(self, object_: object, method: System.IntPtr): ...
    @overload
    def BeginInvoke(self, sender: object, targetHost: str, localCertificates: X509Certificates.X509CertificateCollection, remoteCertificate: X509Certificates.X509Certificate, acceptableIssuers: System.System.Array[str], callback: System.AsyncCallback, object_: object) -> System.IAsyncResult: ...
    @overload
    def EndInvoke(self, result: System.IAsyncResult) -> X509Certificates.X509Certificate: ...
    @overload
    def Invoke(self, sender: object, targetHost: str, localCertificates: X509Certificates.X509CertificateCollection, remoteCertificate: X509Certificates.X509Certificate, acceptableIssuers: System.System.Array[str]) -> X509Certificates.X509Certificate: ...

class ServerCertificateSelectionCallback(System.MulticastDelegate):
    """    """
    def __init__(self, object_: object, method: System.IntPtr): ...
    @overload
    def BeginInvoke(self, sender: object, hostName: str, callback: System.AsyncCallback, object_: object) -> System.IAsyncResult: ...
    @overload
    def EndInvoke(self, result: System.IAsyncResult) -> X509Certificates.X509Certificate: ...
    @overload
    def Invoke(self, sender: object, hostName: str) -> X509Certificates.X509Certificate: ...

class ServerOptionsSelectionCallback(System.MulticastDelegate):
    """    """
    def __init__(self, object_: object, method: System.IntPtr): ...
    @overload
    def BeginInvoke(self, stream: SslStream, clientHelloInfo: SslClientHelloInfo, state: object, cancellationToken: Threading.CancellationToken, callback: System.AsyncCallback, object_: object) -> System.IAsyncResult: ...
    @overload
    def EndInvoke(self, result: System.IAsyncResult) -> Tasks.ValueTask: ...
    @overload
    def Invoke(self, stream: SslStream, clientHelloInfo: SslClientHelloInfo, state: object, cancellationToken: Threading.CancellationToken) -> Tasks.ValueTask: ...

class SslStream(AuthenticatedStream):
    """    """
    @overload
    def __init__(self, innerStream: IO.Stream): ...
    @overload
    def __init__(self, innerStream: IO.Stream, leaveInnerStreamOpen: bool): ...
    @overload
    def __init__(self, innerStream: IO.Stream, leaveInnerStreamOpen: bool, userCertificateValidationCallback: RemoteCertificateValidationCallback): ...
    @overload
    def __init__(self, innerStream: IO.Stream, leaveInnerStreamOpen: bool, userCertificateValidationCallback: RemoteCertificateValidationCallback, userCertificateSelectionCallback: LocalCertificateSelectionCallback): ...
    @overload
    def __init__(self, innerStream: IO.Stream, leaveInnerStreamOpen: bool, userCertificateValidationCallback: RemoteCertificateValidationCallback, userCertificateSelectionCallback: LocalCertificateSelectionCallback, encryptionPolicy: EncryptionPolicy): ...
    @overload
    def AuthenticateAsClient(self, sslClientAuthenticationOptions: SslClientAuthenticationOptions) -> None: ...
    @overload
    def AuthenticateAsClient(self, targetHost: str) -> None: ...
    @overload
    def AuthenticateAsClient(self, targetHost: str, clientCertificates: X509Certificates.X509CertificateCollection, checkCertificateRevocation: bool) -> None: ...
    @overload
    def AuthenticateAsClient(self, targetHost: str, clientCertificates: X509Certificates.X509CertificateCollection, enabledSslProtocols: Authentication.SslProtocols, checkCertificateRevocation: bool) -> None: ...
    @overload
    def AuthenticateAsClientAsync(self, targetHost: str) -> Tasks.Task: ...
    @overload
    def AuthenticateAsClientAsync(self, sslClientAuthenticationOptions: SslClientAuthenticationOptions, cancellationToken: Threading.CancellationToken) -> Tasks.Task: ...
    @overload
    def AuthenticateAsClientAsync(self, targetHost: str, clientCertificates: X509Certificates.X509CertificateCollection, checkCertificateRevocation: bool) -> Tasks.Task: ...
    @overload
    def AuthenticateAsClientAsync(self, targetHost: str, clientCertificates: X509Certificates.X509CertificateCollection, enabledSslProtocols: Authentication.SslProtocols, checkCertificateRevocation: bool) -> Tasks.Task: ...
    @overload
    def AuthenticateAsServer(self, serverCertificate: X509Certificates.X509Certificate) -> None: ...
    @overload
    def AuthenticateAsServer(self, sslServerAuthenticationOptions: SslServerAuthenticationOptions) -> None: ...
    @overload
    def AuthenticateAsServer(self, serverCertificate: X509Certificates.X509Certificate, clientCertificateRequired: bool, checkCertificateRevocation: bool) -> None: ...
    @overload
    def AuthenticateAsServer(self, serverCertificate: X509Certificates.X509Certificate, clientCertificateRequired: bool, enabledSslProtocols: Authentication.SslProtocols, checkCertificateRevocation: bool) -> None: ...
    @overload
    def AuthenticateAsServerAsync(self, serverCertificate: X509Certificates.X509Certificate) -> Tasks.Task: ...
    @overload
    def AuthenticateAsServerAsync(self, sslServerAuthenticationOptions: SslServerAuthenticationOptions, cancellationToken: Threading.CancellationToken) -> Tasks.Task: ...
    @overload
    def AuthenticateAsServerAsync(self, serverCertificate: X509Certificates.X509Certificate, clientCertificateRequired: bool, checkCertificateRevocation: bool) -> Tasks.Task: ...
    @overload
    def AuthenticateAsServerAsync(self, optionsCallback: ServerOptionsSelectionCallback, state: object, cancellationToken: Threading.CancellationToken) -> Tasks.Task: ...
    @overload
    def AuthenticateAsServerAsync(self, serverCertificate: X509Certificates.X509Certificate, clientCertificateRequired: bool, enabledSslProtocols: Authentication.SslProtocols, checkCertificateRevocation: bool) -> Tasks.Task: ...
    @overload
    def BeginAuthenticateAsClient(self, targetHost: str, asyncCallback: System.AsyncCallback, asyncState: object) -> System.IAsyncResult: ...
    @overload
    def BeginAuthenticateAsClient(self, targetHost: str, clientCertificates: X509Certificates.X509CertificateCollection, checkCertificateRevocation: bool, asyncCallback: System.AsyncCallback, asyncState: object) -> System.IAsyncResult: ...
    @overload
    def BeginAuthenticateAsClient(self, targetHost: str, clientCertificates: X509Certificates.X509CertificateCollection, enabledSslProtocols: Authentication.SslProtocols, checkCertificateRevocation: bool, asyncCallback: System.AsyncCallback, asyncState: object) -> System.IAsyncResult: ...
    @overload
    def BeginAuthenticateAsServer(self, serverCertificate: X509Certificates.X509Certificate, asyncCallback: System.AsyncCallback, asyncState: object) -> System.IAsyncResult: ...
    @overload
    def BeginAuthenticateAsServer(self, serverCertificate: X509Certificates.X509Certificate, clientCertificateRequired: bool, checkCertificateRevocation: bool, asyncCallback: System.AsyncCallback, asyncState: object) -> System.IAsyncResult: ...
    @overload
    def BeginAuthenticateAsServer(self, serverCertificate: X509Certificates.X509Certificate, clientCertificateRequired: bool, enabledSslProtocols: Authentication.SslProtocols, checkCertificateRevocation: bool, asyncCallback: System.AsyncCallback, asyncState: object) -> System.IAsyncResult: ...
    @overload
    def BeginRead(self, buffer: System.System.Array[System.Byte], offset: int, count: int, asyncCallback: System.AsyncCallback, asyncState: object) -> System.IAsyncResult: ...
    @overload
    def BeginWrite(self, buffer: System.System.Array[System.Byte], offset: int, count: int, asyncCallback: System.AsyncCallback, asyncState: object) -> System.IAsyncResult: ...
    @overload
    def DisposeAsync() -> Tasks.ValueTask: ...
    @overload
    def EndAuthenticateAsClient(self, asyncResult: System.IAsyncResult) -> None: ...
    @overload
    def EndAuthenticateAsServer(self, asyncResult: System.IAsyncResult) -> None: ...
    @overload
    def EndRead(self, asyncResult: System.IAsyncResult) -> int: ...
    @overload
    def EndWrite(self, asyncResult: System.IAsyncResult) -> None: ...
    @overload
    def Flush() -> None: ...
    @overload
    def FlushAsync(self, cancellationToken: Threading.CancellationToken) -> Tasks.Task: ...
    @property
    def CanRead(self) -> bool: ...
    @property
    def CanSeek(self) -> bool: ...
    @property
    def CanTimeout(self) -> bool: ...
    @property
    def CanWrite(self) -> bool: ...
    @property
    def CheckCertRevocationStatus(self) -> bool: ...
    @property
    def CipherAlgorithm(self) -> Authentication.CipherAlgorithmType: ...
    @property
    def CipherStrength(self) -> int: ...
    @property
    def HashAlgorithm(self) -> Authentication.HashAlgorithmType: ...
    @property
    def HashStrength(self) -> int: ...
    @property
    def IsAuthenticated(self) -> bool: ...
    @property
    def IsEncrypted(self) -> bool: ...
    @property
    def IsMutuallyAuthenticated(self) -> bool: ...
    @property
    def IsServer(self) -> bool: ...
    @property
    def IsSigned(self) -> bool: ...
    @property
    def KeyExchangeAlgorithm(self) -> Authentication.ExchangeAlgorithmType: ...
    @property
    def KeyExchangeStrength(self) -> int: ...
    @property
    def Length(self) -> System.Int64: ...
    @property
    def LocalCertificate(self) -> X509Certificates.X509Certificate: ...
    @property
    def NegotiatedApplicationProtocol(self) -> SslApplicationProtocol: ...
    @property
    def NegotiatedCipherSuite(self) -> TlsCipherSuite: ...
    @property
    def Position(self) -> System.Int64: ...
    @property
    def ReadTimeout(self) -> int: ...
    @property
    def RemoteCertificate(self) -> X509Certificates.X509Certificate: ...
    @property
    def SslProtocol(self) -> Authentication.SslProtocols: ...
    @property
    def TargetHostName(self) -> str: ...
    @property
    def TransportContext(self) -> Net.TransportContext: ...
    @property
    def WriteTimeout(self) -> int: ...
    @overload
    def NegotiateClientCertificateAsync(self, cancellationToken: Threading.CancellationToken) -> Tasks.Task: ...
    @overload
    def Read(self, buffer: System.System.Array[System.Byte], offset: int, count: int) -> int: ...
    @overload
    def ReadAsync(self, buffer: System.Memory, cancellationToken: Threading.CancellationToken) -> Tasks.ValueTask: ...
    @overload
    def ReadAsync(self, buffer: System.System.Array[System.Byte], offset: int, count: int, cancellationToken: Threading.CancellationToken) -> Tasks.Task: ...
    @overload
    def ReadByte() -> int: ...
    @overload
    def Seek(self, offset: System.Int64, origin: IO.SeekOrigin) -> System.Int64: ...
    @Position.setter
    def Position(self, value: System.Void): ...
    @ReadTimeout.setter
    def ReadTimeout(self, value: System.Void): ...
    @WriteTimeout.setter
    def WriteTimeout(self, value: System.Void): ...
    @overload
    def SetLength(self, value: System.Int64) -> None: ...
    @overload
    def ShutdownAsync() -> Tasks.Task: ...
    @overload
    def Write(self, buffer: System.System.Array[System.Byte]) -> None: ...
    @overload
    def Write(self, buffer: System.System.Array[System.Byte], offset: int, count: int) -> None: ...
    @overload
    def WriteAsync(self, buffer: System.ReadOnlyMemory, cancellationToken: Threading.CancellationToken) -> Tasks.ValueTask: ...
    @overload
    def WriteAsync(self, buffer: System.System.Array[System.Byte], offset: int, count: int, cancellationToken: Threading.CancellationToken) -> Tasks.Task: ...

class SslStreamCertificateContext(object):
    """    """
    @property
    def Certificate(self) -> X509Certificates.X509Certificate2: ...
    @property
    def IntermediateCertificates(self) -> X509Certificates.System.Array[X509Certificates.X509Certificate2]: ...
    @overload
    @staticmethod
    def Create(target: X509Certificates.X509Certificate2, additionalCertificates: X509Certificates.X509Certificate2Collection, offline: bool) -> SslStreamCertificateContext: ...
    @overload
    @staticmethod
    def Create(target: X509Certificates.X509Certificate2, additionalCertificates: X509Certificates.X509Certificate2Collection, offline: bool, trust: SslCertificateTrust) -> SslStreamCertificateContext: ...

class NegotiateStream(AuthenticatedStream):
    """    """
    @overload
    def __init__(self, innerStream: IO.Stream): ...
    @overload
    def __init__(self, innerStream: IO.Stream, leaveInnerStreamOpen: bool): ...
    @overload
    def AuthenticateAsClient() -> None: ...
    @overload
    def AuthenticateAsClient(self, credential: Net.NetworkCredential, targetName: str) -> None: ...
    @overload
    def AuthenticateAsClient(self, credential: Net.NetworkCredential, binding: ExtendedProtection.ChannelBinding, targetName: str) -> None: ...
    @overload
    def AuthenticateAsClient(self, credential: Net.NetworkCredential, targetName: str, requiredProtectionLevel: ProtectionLevel, allowedImpersonationLevel: Principal.TokenImpersonationLevel) -> None: ...
    @overload
    def AuthenticateAsClient(self, credential: Net.NetworkCredential, binding: ExtendedProtection.ChannelBinding, targetName: str, requiredProtectionLevel: ProtectionLevel, allowedImpersonationLevel: Principal.TokenImpersonationLevel) -> None: ...
    @overload
    def AuthenticateAsClientAsync() -> Tasks.Task: ...
    @overload
    def AuthenticateAsClientAsync(self, credential: Net.NetworkCredential, targetName: str) -> Tasks.Task: ...
    @overload
    def AuthenticateAsClientAsync(self, credential: Net.NetworkCredential, binding: ExtendedProtection.ChannelBinding, targetName: str) -> Tasks.Task: ...
    @overload
    def AuthenticateAsClientAsync(self, credential: Net.NetworkCredential, targetName: str, requiredProtectionLevel: ProtectionLevel, allowedImpersonationLevel: Principal.TokenImpersonationLevel) -> Tasks.Task: ...
    @overload
    def AuthenticateAsClientAsync(self, credential: Net.NetworkCredential, binding: ExtendedProtection.ChannelBinding, targetName: str, requiredProtectionLevel: ProtectionLevel, allowedImpersonationLevel: Principal.TokenImpersonationLevel) -> Tasks.Task: ...
    @overload
    def AuthenticateAsServer() -> None: ...
    @overload
    def AuthenticateAsServer(self, policy: ExtendedProtection.ExtendedProtectionPolicy) -> None: ...
    @overload
    def AuthenticateAsServer(self, credential: Net.NetworkCredential, requiredProtectionLevel: ProtectionLevel, requiredImpersonationLevel: Principal.TokenImpersonationLevel) -> None: ...
    @overload
    def AuthenticateAsServer(self, credential: Net.NetworkCredential, policy: ExtendedProtection.ExtendedProtectionPolicy, requiredProtectionLevel: ProtectionLevel, requiredImpersonationLevel: Principal.TokenImpersonationLevel) -> None: ...
    @overload
    def AuthenticateAsServerAsync() -> Tasks.Task: ...
    @overload
    def AuthenticateAsServerAsync(self, policy: ExtendedProtection.ExtendedProtectionPolicy) -> Tasks.Task: ...
    @overload
    def AuthenticateAsServerAsync(self, credential: Net.NetworkCredential, requiredProtectionLevel: ProtectionLevel, requiredImpersonationLevel: Principal.TokenImpersonationLevel) -> Tasks.Task: ...
    @overload
    def AuthenticateAsServerAsync(self, credential: Net.NetworkCredential, policy: ExtendedProtection.ExtendedProtectionPolicy, requiredProtectionLevel: ProtectionLevel, requiredImpersonationLevel: Principal.TokenImpersonationLevel) -> Tasks.Task: ...
    @overload
    def BeginAuthenticateAsClient(self, asyncCallback: System.AsyncCallback, asyncState: object) -> System.IAsyncResult: ...
    @overload
    def BeginAuthenticateAsClient(self, credential: Net.NetworkCredential, targetName: str, asyncCallback: System.AsyncCallback, asyncState: object) -> System.IAsyncResult: ...
    @overload
    def BeginAuthenticateAsClient(self, credential: Net.NetworkCredential, binding: ExtendedProtection.ChannelBinding, targetName: str, asyncCallback: System.AsyncCallback, asyncState: object) -> System.IAsyncResult: ...
    @overload
    def BeginAuthenticateAsClient(self, credential: Net.NetworkCredential, targetName: str, requiredProtectionLevel: ProtectionLevel, allowedImpersonationLevel: Principal.TokenImpersonationLevel, asyncCallback: System.AsyncCallback, asyncState: object) -> System.IAsyncResult: ...
    @overload
    def BeginAuthenticateAsClient(self, credential: Net.NetworkCredential, binding: ExtendedProtection.ChannelBinding, targetName: str, requiredProtectionLevel: ProtectionLevel, allowedImpersonationLevel: Principal.TokenImpersonationLevel, asyncCallback: System.AsyncCallback, asyncState: object) -> System.IAsyncResult: ...
    @overload
    def BeginAuthenticateAsServer(self, asyncCallback: System.AsyncCallback, asyncState: object) -> System.IAsyncResult: ...
    @overload
    def BeginAuthenticateAsServer(self, policy: ExtendedProtection.ExtendedProtectionPolicy, asyncCallback: System.AsyncCallback, asyncState: object) -> System.IAsyncResult: ...
    @overload
    def BeginAuthenticateAsServer(self, credential: Net.NetworkCredential, requiredProtectionLevel: ProtectionLevel, requiredImpersonationLevel: Principal.TokenImpersonationLevel, asyncCallback: System.AsyncCallback, asyncState: object) -> System.IAsyncResult: ...
    @overload
    def BeginAuthenticateAsServer(self, credential: Net.NetworkCredential, policy: ExtendedProtection.ExtendedProtectionPolicy, requiredProtectionLevel: ProtectionLevel, requiredImpersonationLevel: Principal.TokenImpersonationLevel, asyncCallback: System.AsyncCallback, asyncState: object) -> System.IAsyncResult: ...
    @overload
    def BeginRead(self, buffer: System.System.Array[System.Byte], offset: int, count: int, asyncCallback: System.AsyncCallback, asyncState: object) -> System.IAsyncResult: ...
    @overload
    def BeginWrite(self, buffer: System.System.Array[System.Byte], offset: int, count: int, asyncCallback: System.AsyncCallback, asyncState: object) -> System.IAsyncResult: ...
    @overload
    def DisposeAsync() -> Tasks.ValueTask: ...
    @overload
    def EndAuthenticateAsClient(self, asyncResult: System.IAsyncResult) -> None: ...
    @overload
    def EndAuthenticateAsServer(self, asyncResult: System.IAsyncResult) -> None: ...
    @overload
    def EndRead(self, asyncResult: System.IAsyncResult) -> int: ...
    @overload
    def EndWrite(self, asyncResult: System.IAsyncResult) -> None: ...
    @overload
    def Flush() -> None: ...
    @overload
    def FlushAsync(self, cancellationToken: Threading.CancellationToken) -> Tasks.Task: ...
    @property
    def CanRead(self) -> bool: ...
    @property
    def CanSeek(self) -> bool: ...
    @property
    def CanTimeout(self) -> bool: ...
    @property
    def CanWrite(self) -> bool: ...
    @property
    def ImpersonationLevel(self) -> Principal.TokenImpersonationLevel: ...
    @property
    def IsAuthenticated(self) -> bool: ...
    @property
    def IsEncrypted(self) -> bool: ...
    @property
    def IsMutuallyAuthenticated(self) -> bool: ...
    @property
    def IsServer(self) -> bool: ...
    @property
    def IsSigned(self) -> bool: ...
    @property
    def Length(self) -> System.Int64: ...
    @property
    def Position(self) -> System.Int64: ...
    @property
    def ReadTimeout(self) -> int: ...
    @property
    def RemoteIdentity(self) -> Principal.IIdentity: ...
    @property
    def WriteTimeout(self) -> int: ...
    @overload
    def Read(self, buffer: System.System.Array[System.Byte], offset: int, count: int) -> int: ...
    @overload
    def ReadAsync(self, buffer: System.Memory, cancellationToken: Threading.CancellationToken) -> Tasks.ValueTask: ...
    @overload
    def ReadAsync(self, buffer: System.System.Array[System.Byte], offset: int, count: int, cancellationToken: Threading.CancellationToken) -> Tasks.Task: ...
    @overload
    def Seek(self, offset: System.Int64, origin: IO.SeekOrigin) -> System.Int64: ...
    @Position.setter
    def Position(self, value: System.Void): ...
    @ReadTimeout.setter
    def ReadTimeout(self, value: System.Void): ...
    @WriteTimeout.setter
    def WriteTimeout(self, value: System.Void): ...
    @overload
    def SetLength(self, value: System.Int64) -> None: ...
    @overload
    def Write(self, buffer: System.System.Array[System.Byte], offset: int, count: int) -> None: ...
    @overload
    def WriteAsync(self, buffer: System.ReadOnlyMemory, cancellationToken: Threading.CancellationToken) -> Tasks.ValueTask: ...
    @overload
    def WriteAsync(self, buffer: System.System.Array[System.Byte], offset: int, count: int, cancellationToken: Threading.CancellationToken) -> Tasks.Task: ...

class TlsCipherSuite(enum.Enum):
    TLS_NULL_WITH_NULL_NULL = 0
    TLS_RSA_WITH_NULL_MD5 = 1
    TLS_RSA_WITH_NULL_SHA = 2
    TLS_RSA_EXPORT_WITH_RC4_40_MD5 = 3
    TLS_RSA_WITH_RC4_128_MD5 = 4
    TLS_RSA_WITH_RC4_128_SHA = 5
    TLS_RSA_EXPORT_WITH_RC2_CBC_40_MD5 = 6
    TLS_RSA_WITH_IDEA_CBC_SHA = 7
    TLS_RSA_EXPORT_WITH_DES40_CBC_SHA = 8
    TLS_RSA_WITH_DES_CBC_SHA = 9
    TLS_RSA_WITH_3DES_EDE_CBC_SHA = 10
    TLS_DH_DSS_EXPORT_WITH_DES40_CBC_SHA = 11
    TLS_DH_DSS_WITH_DES_CBC_SHA = 12
    TLS_DH_DSS_WITH_3DES_EDE_CBC_SHA = 13
    TLS_DH_RSA_EXPORT_WITH_DES40_CBC_SHA = 14
    TLS_DH_RSA_WITH_DES_CBC_SHA = 15
    TLS_DH_RSA_WITH_3DES_EDE_CBC_SHA = 16
    TLS_DHE_DSS_EXPORT_WITH_DES40_CBC_SHA = 17
    TLS_DHE_DSS_WITH_DES_CBC_SHA = 18
    TLS_DHE_DSS_WITH_3DES_EDE_CBC_SHA = 19
    TLS_DHE_RSA_EXPORT_WITH_DES40_CBC_SHA = 20
    TLS_DHE_RSA_WITH_DES_CBC_SHA = 21
    TLS_DHE_RSA_WITH_3DES_EDE_CBC_SHA = 22
    TLS_DH_anon_EXPORT_WITH_RC4_40_MD5 = 23
    TLS_DH_anon_WITH_RC4_128_MD5 = 24
    TLS_DH_anon_EXPORT_WITH_DES40_CBC_SHA = 25
    TLS_DH_anon_WITH_DES_CBC_SHA = 26
    TLS_DH_anon_WITH_3DES_EDE_CBC_SHA = 27
    TLS_KRB5_WITH_DES_CBC_SHA = 30
    TLS_KRB5_WITH_3DES_EDE_CBC_SHA = 31
    TLS_KRB5_WITH_RC4_128_SHA = 32
    TLS_KRB5_WITH_IDEA_CBC_SHA = 33
    TLS_KRB5_WITH_DES_CBC_MD5 = 34
    TLS_KRB5_WITH_3DES_EDE_CBC_MD5 = 35
    TLS_KRB5_WITH_RC4_128_MD5 = 36
    TLS_KRB5_WITH_IDEA_CBC_MD5 = 37
    TLS_KRB5_EXPORT_WITH_DES_CBC_40_SHA = 38
    TLS_KRB5_EXPORT_WITH_RC2_CBC_40_SHA = 39
    TLS_KRB5_EXPORT_WITH_RC4_40_SHA = 40
    TLS_KRB5_EXPORT_WITH_DES_CBC_40_MD5 = 41
    TLS_KRB5_EXPORT_WITH_RC2_CBC_40_MD5 = 42
    TLS_KRB5_EXPORT_WITH_RC4_40_MD5 = 43
    TLS_PSK_WITH_NULL_SHA = 44
    TLS_DHE_PSK_WITH_NULL_SHA = 45
    TLS_RSA_PSK_WITH_NULL_SHA = 46
    TLS_RSA_WITH_AES_128_CBC_SHA = 47
    TLS_DH_DSS_WITH_AES_128_CBC_SHA = 48
    TLS_DH_RSA_WITH_AES_128_CBC_SHA = 49
    TLS_DHE_DSS_WITH_AES_128_CBC_SHA = 50
    TLS_DHE_RSA_WITH_AES_128_CBC_SHA = 51
    TLS_DH_anon_WITH_AES_128_CBC_SHA = 52
    TLS_RSA_WITH_AES_256_CBC_SHA = 53
    TLS_DH_DSS_WITH_AES_256_CBC_SHA = 54
    TLS_DH_RSA_WITH_AES_256_CBC_SHA = 55
    TLS_DHE_DSS_WITH_AES_256_CBC_SHA = 56
    TLS_DHE_RSA_WITH_AES_256_CBC_SHA = 57
    TLS_DH_anon_WITH_AES_256_CBC_SHA = 58
    TLS_RSA_WITH_NULL_SHA256 = 59
    TLS_RSA_WITH_AES_128_CBC_SHA256 = 60
    TLS_RSA_WITH_AES_256_CBC_SHA256 = 61
    TLS_DH_DSS_WITH_AES_128_CBC_SHA256 = 62
    TLS_DH_RSA_WITH_AES_128_CBC_SHA256 = 63
    TLS_DHE_DSS_WITH_AES_128_CBC_SHA256 = 64
    TLS_RSA_WITH_CAMELLIA_128_CBC_SHA = 65
    TLS_DH_DSS_WITH_CAMELLIA_128_CBC_SHA = 66
    TLS_DH_RSA_WITH_CAMELLIA_128_CBC_SHA = 67
    TLS_DHE_DSS_WITH_CAMELLIA_128_CBC_SHA = 68
    TLS_DHE_RSA_WITH_CAMELLIA_128_CBC_SHA = 69
    TLS_DH_anon_WITH_CAMELLIA_128_CBC_SHA = 70
    TLS_DHE_RSA_WITH_AES_128_CBC_SHA256 = 103
    TLS_DH_DSS_WITH_AES_256_CBC_SHA256 = 104
    TLS_DH_RSA_WITH_AES_256_CBC_SHA256 = 105
    TLS_DHE_DSS_WITH_AES_256_CBC_SHA256 = 106
    TLS_DHE_RSA_WITH_AES_256_CBC_SHA256 = 107
    TLS_DH_anon_WITH_AES_128_CBC_SHA256 = 108
    TLS_DH_anon_WITH_AES_256_CBC_SHA256 = 109
    TLS_RSA_WITH_CAMELLIA_256_CBC_SHA = 132
    TLS_DH_DSS_WITH_CAMELLIA_256_CBC_SHA = 133
    TLS_DH_RSA_WITH_CAMELLIA_256_CBC_SHA = 134
    TLS_DHE_DSS_WITH_CAMELLIA_256_CBC_SHA = 135
    TLS_DHE_RSA_WITH_CAMELLIA_256_CBC_SHA = 136
    TLS_DH_anon_WITH_CAMELLIA_256_CBC_SHA = 137
    TLS_PSK_WITH_RC4_128_SHA = 138
    TLS_PSK_WITH_3DES_EDE_CBC_SHA = 139
    TLS_PSK_WITH_AES_128_CBC_SHA = 140
    TLS_PSK_WITH_AES_256_CBC_SHA = 141
    TLS_DHE_PSK_WITH_RC4_128_SHA = 142
    TLS_DHE_PSK_WITH_3DES_EDE_CBC_SHA = 143
    TLS_DHE_PSK_WITH_AES_128_CBC_SHA = 144
    TLS_DHE_PSK_WITH_AES_256_CBC_SHA = 145
    TLS_RSA_PSK_WITH_RC4_128_SHA = 146
    TLS_RSA_PSK_WITH_3DES_EDE_CBC_SHA = 147
    TLS_RSA_PSK_WITH_AES_128_CBC_SHA = 148
    TLS_RSA_PSK_WITH_AES_256_CBC_SHA = 149
    TLS_RSA_WITH_SEED_CBC_SHA = 150
    TLS_DH_DSS_WITH_SEED_CBC_SHA = 151
    TLS_DH_RSA_WITH_SEED_CBC_SHA = 152
    TLS_DHE_DSS_WITH_SEED_CBC_SHA = 153
    TLS_DHE_RSA_WITH_SEED_CBC_SHA = 154
    TLS_DH_anon_WITH_SEED_CBC_SHA = 155
    TLS_RSA_WITH_AES_128_GCM_SHA256 = 156
    TLS_RSA_WITH_AES_256_GCM_SHA384 = 157
    TLS_DHE_RSA_WITH_AES_128_GCM_SHA256 = 158
    TLS_DHE_RSA_WITH_AES_256_GCM_SHA384 = 159
    TLS_DH_RSA_WITH_AES_128_GCM_SHA256 = 160
    TLS_DH_RSA_WITH_AES_256_GCM_SHA384 = 161
    TLS_DHE_DSS_WITH_AES_128_GCM_SHA256 = 162
    TLS_DHE_DSS_WITH_AES_256_GCM_SHA384 = 163
    TLS_DH_DSS_WITH_AES_128_GCM_SHA256 = 164
    TLS_DH_DSS_WITH_AES_256_GCM_SHA384 = 165
    TLS_DH_anon_WITH_AES_128_GCM_SHA256 = 166
    TLS_DH_anon_WITH_AES_256_GCM_SHA384 = 167
    TLS_PSK_WITH_AES_128_GCM_SHA256 = 168
    TLS_PSK_WITH_AES_256_GCM_SHA384 = 169
    TLS_DHE_PSK_WITH_AES_128_GCM_SHA256 = 170
    TLS_DHE_PSK_WITH_AES_256_GCM_SHA384 = 171
    TLS_RSA_PSK_WITH_AES_128_GCM_SHA256 = 172
    TLS_RSA_PSK_WITH_AES_256_GCM_SHA384 = 173
    TLS_PSK_WITH_AES_128_CBC_SHA256 = 174
    TLS_PSK_WITH_AES_256_CBC_SHA384 = 175
    TLS_PSK_WITH_NULL_SHA256 = 176
    TLS_PSK_WITH_NULL_SHA384 = 177
    TLS_DHE_PSK_WITH_AES_128_CBC_SHA256 = 178
    TLS_DHE_PSK_WITH_AES_256_CBC_SHA384 = 179
    TLS_DHE_PSK_WITH_NULL_SHA256 = 180
    TLS_DHE_PSK_WITH_NULL_SHA384 = 181
    TLS_RSA_PSK_WITH_AES_128_CBC_SHA256 = 182
    TLS_RSA_PSK_WITH_AES_256_CBC_SHA384 = 183
    TLS_RSA_PSK_WITH_NULL_SHA256 = 184
    TLS_RSA_PSK_WITH_NULL_SHA384 = 185
    TLS_RSA_WITH_CAMELLIA_128_CBC_SHA256 = 186
    TLS_DH_DSS_WITH_CAMELLIA_128_CBC_SHA256 = 187
    TLS_DH_RSA_WITH_CAMELLIA_128_CBC_SHA256 = 188
    TLS_DHE_DSS_WITH_CAMELLIA_128_CBC_SHA256 = 189
    TLS_DHE_RSA_WITH_CAMELLIA_128_CBC_SHA256 = 190
    TLS_DH_anon_WITH_CAMELLIA_128_CBC_SHA256 = 191
    TLS_RSA_WITH_CAMELLIA_256_CBC_SHA256 = 192
    TLS_DH_DSS_WITH_CAMELLIA_256_CBC_SHA256 = 193
    TLS_DH_RSA_WITH_CAMELLIA_256_CBC_SHA256 = 194
    TLS_DHE_DSS_WITH_CAMELLIA_256_CBC_SHA256 = 195
    TLS_DHE_RSA_WITH_CAMELLIA_256_CBC_SHA256 = 196
    TLS_DH_anon_WITH_CAMELLIA_256_CBC_SHA256 = 197
    TLS_AES_128_GCM_SHA256 = 4865
    TLS_AES_256_GCM_SHA384 = 4866
    TLS_CHACHA20_POLY1305_SHA256 = 4867
    TLS_AES_128_CCM_SHA256 = 4868
    TLS_AES_128_CCM_8_SHA256 = 4869
    TLS_ECDH_ECDSA_WITH_NULL_SHA = 49153
    TLS_ECDH_ECDSA_WITH_RC4_128_SHA = 49154
    TLS_ECDH_ECDSA_WITH_3DES_EDE_CBC_SHA = 49155
    TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA = 49156
    TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA = 49157
    TLS_ECDHE_ECDSA_WITH_NULL_SHA = 49158
    TLS_ECDHE_ECDSA_WITH_RC4_128_SHA = 49159
    TLS_ECDHE_ECDSA_WITH_3DES_EDE_CBC_SHA = 49160
    TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA = 49161
    TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA = 49162
    TLS_ECDH_RSA_WITH_NULL_SHA = 49163
    TLS_ECDH_RSA_WITH_RC4_128_SHA = 49164
    TLS_ECDH_RSA_WITH_3DES_EDE_CBC_SHA = 49165
    TLS_ECDH_RSA_WITH_AES_128_CBC_SHA = 49166
    TLS_ECDH_RSA_WITH_AES_256_CBC_SHA = 49167
    TLS_ECDHE_RSA_WITH_NULL_SHA = 49168
    TLS_ECDHE_RSA_WITH_RC4_128_SHA = 49169
    TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA = 49170
    TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA = 49171
    TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA = 49172
    TLS_ECDH_anon_WITH_NULL_SHA = 49173
    TLS_ECDH_anon_WITH_RC4_128_SHA = 49174
    TLS_ECDH_anon_WITH_3DES_EDE_CBC_SHA = 49175
    TLS_ECDH_anon_WITH_AES_128_CBC_SHA = 49176
    TLS_ECDH_anon_WITH_AES_256_CBC_SHA = 49177
    TLS_SRP_SHA_WITH_3DES_EDE_CBC_SHA = 49178
    TLS_SRP_SHA_RSA_WITH_3DES_EDE_CBC_SHA = 49179
    TLS_SRP_SHA_DSS_WITH_3DES_EDE_CBC_SHA = 49180
    TLS_SRP_SHA_WITH_AES_128_CBC_SHA = 49181
    TLS_SRP_SHA_RSA_WITH_AES_128_CBC_SHA = 49182
    TLS_SRP_SHA_DSS_WITH_AES_128_CBC_SHA = 49183
    TLS_SRP_SHA_WITH_AES_256_CBC_SHA = 49184
    TLS_SRP_SHA_RSA_WITH_AES_256_CBC_SHA = 49185
    TLS_SRP_SHA_DSS_WITH_AES_256_CBC_SHA = 49186
    TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256 = 49187
    TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384 = 49188
    TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA256 = 49189
    TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA384 = 49190
    TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 = 49191
    TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 = 49192
    TLS_ECDH_RSA_WITH_AES_128_CBC_SHA256 = 49193
    TLS_ECDH_RSA_WITH_AES_256_CBC_SHA384 = 49194
    TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 = 49195
    TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 = 49196
    TLS_ECDH_ECDSA_WITH_AES_128_GCM_SHA256 = 49197
    TLS_ECDH_ECDSA_WITH_AES_256_GCM_SHA384 = 49198
    TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 = 49199
    TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 = 49200
    TLS_ECDH_RSA_WITH_AES_128_GCM_SHA256 = 49201
    TLS_ECDH_RSA_WITH_AES_256_GCM_SHA384 = 49202
    TLS_ECDHE_PSK_WITH_RC4_128_SHA = 49203
    TLS_ECDHE_PSK_WITH_3DES_EDE_CBC_SHA = 49204
    TLS_ECDHE_PSK_WITH_AES_128_CBC_SHA = 49205
    TLS_ECDHE_PSK_WITH_AES_256_CBC_SHA = 49206
    TLS_ECDHE_PSK_WITH_AES_128_CBC_SHA256 = 49207
    TLS_ECDHE_PSK_WITH_AES_256_CBC_SHA384 = 49208
    TLS_ECDHE_PSK_WITH_NULL_SHA = 49209
    TLS_ECDHE_PSK_WITH_NULL_SHA256 = 49210
    TLS_ECDHE_PSK_WITH_NULL_SHA384 = 49211
    TLS_RSA_WITH_ARIA_128_CBC_SHA256 = 49212
    TLS_RSA_WITH_ARIA_256_CBC_SHA384 = 49213
    TLS_DH_DSS_WITH_ARIA_128_CBC_SHA256 = 49214
    TLS_DH_DSS_WITH_ARIA_256_CBC_SHA384 = 49215
    TLS_DH_RSA_WITH_ARIA_128_CBC_SHA256 = 49216
    TLS_DH_RSA_WITH_ARIA_256_CBC_SHA384 = 49217
    TLS_DHE_DSS_WITH_ARIA_128_CBC_SHA256 = 49218
    TLS_DHE_DSS_WITH_ARIA_256_CBC_SHA384 = 49219
    TLS_DHE_RSA_WITH_ARIA_128_CBC_SHA256 = 49220
    TLS_DHE_RSA_WITH_ARIA_256_CBC_SHA384 = 49221
    TLS_DH_anon_WITH_ARIA_128_CBC_SHA256 = 49222
    TLS_DH_anon_WITH_ARIA_256_CBC_SHA384 = 49223
    TLS_ECDHE_ECDSA_WITH_ARIA_128_CBC_SHA256 = 49224
    TLS_ECDHE_ECDSA_WITH_ARIA_256_CBC_SHA384 = 49225
    TLS_ECDH_ECDSA_WITH_ARIA_128_CBC_SHA256 = 49226
    TLS_ECDH_ECDSA_WITH_ARIA_256_CBC_SHA384 = 49227
    TLS_ECDHE_RSA_WITH_ARIA_128_CBC_SHA256 = 49228
    TLS_ECDHE_RSA_WITH_ARIA_256_CBC_SHA384 = 49229
    TLS_ECDH_RSA_WITH_ARIA_128_CBC_SHA256 = 49230
    TLS_ECDH_RSA_WITH_ARIA_256_CBC_SHA384 = 49231
    TLS_RSA_WITH_ARIA_128_GCM_SHA256 = 49232
    TLS_RSA_WITH_ARIA_256_GCM_SHA384 = 49233
    TLS_DHE_RSA_WITH_ARIA_128_GCM_SHA256 = 49234
    TLS_DHE_RSA_WITH_ARIA_256_GCM_SHA384 = 49235
    TLS_DH_RSA_WITH_ARIA_128_GCM_SHA256 = 49236
    TLS_DH_RSA_WITH_ARIA_256_GCM_SHA384 = 49237
    TLS_DHE_DSS_WITH_ARIA_128_GCM_SHA256 = 49238
    TLS_DHE_DSS_WITH_ARIA_256_GCM_SHA384 = 49239
    TLS_DH_DSS_WITH_ARIA_128_GCM_SHA256 = 49240
    TLS_DH_DSS_WITH_ARIA_256_GCM_SHA384 = 49241
    TLS_DH_anon_WITH_ARIA_128_GCM_SHA256 = 49242
    TLS_DH_anon_WITH_ARIA_256_GCM_SHA384 = 49243
    TLS_ECDHE_ECDSA_WITH_ARIA_128_GCM_SHA256 = 49244
    TLS_ECDHE_ECDSA_WITH_ARIA_256_GCM_SHA384 = 49245
    TLS_ECDH_ECDSA_WITH_ARIA_128_GCM_SHA256 = 49246
    TLS_ECDH_ECDSA_WITH_ARIA_256_GCM_SHA384 = 49247
    TLS_ECDHE_RSA_WITH_ARIA_128_GCM_SHA256 = 49248
    TLS_ECDHE_RSA_WITH_ARIA_256_GCM_SHA384 = 49249
    TLS_ECDH_RSA_WITH_ARIA_128_GCM_SHA256 = 49250
    TLS_ECDH_RSA_WITH_ARIA_256_GCM_SHA384 = 49251
    TLS_PSK_WITH_ARIA_128_CBC_SHA256 = 49252
    TLS_PSK_WITH_ARIA_256_CBC_SHA384 = 49253
    TLS_DHE_PSK_WITH_ARIA_128_CBC_SHA256 = 49254
    TLS_DHE_PSK_WITH_ARIA_256_CBC_SHA384 = 49255
    TLS_RSA_PSK_WITH_ARIA_128_CBC_SHA256 = 49256
    TLS_RSA_PSK_WITH_ARIA_256_CBC_SHA384 = 49257
    TLS_PSK_WITH_ARIA_128_GCM_SHA256 = 49258
    TLS_PSK_WITH_ARIA_256_GCM_SHA384 = 49259
    TLS_DHE_PSK_WITH_ARIA_128_GCM_SHA256 = 49260
    TLS_DHE_PSK_WITH_ARIA_256_GCM_SHA384 = 49261
    TLS_RSA_PSK_WITH_ARIA_128_GCM_SHA256 = 49262
    TLS_RSA_PSK_WITH_ARIA_256_GCM_SHA384 = 49263
    TLS_ECDHE_PSK_WITH_ARIA_128_CBC_SHA256 = 49264
    TLS_ECDHE_PSK_WITH_ARIA_256_CBC_SHA384 = 49265
    TLS_ECDHE_ECDSA_WITH_CAMELLIA_128_CBC_SHA256 = 49266
    TLS_ECDHE_ECDSA_WITH_CAMELLIA_256_CBC_SHA384 = 49267
    TLS_ECDH_ECDSA_WITH_CAMELLIA_128_CBC_SHA256 = 49268
    TLS_ECDH_ECDSA_WITH_CAMELLIA_256_CBC_SHA384 = 49269
    TLS_ECDHE_RSA_WITH_CAMELLIA_128_CBC_SHA256 = 49270
    TLS_ECDHE_RSA_WITH_CAMELLIA_256_CBC_SHA384 = 49271
    TLS_ECDH_RSA_WITH_CAMELLIA_128_CBC_SHA256 = 49272
    TLS_ECDH_RSA_WITH_CAMELLIA_256_CBC_SHA384 = 49273
    TLS_RSA_WITH_CAMELLIA_128_GCM_SHA256 = 49274
    TLS_RSA_WITH_CAMELLIA_256_GCM_SHA384 = 49275
    TLS_DHE_RSA_WITH_CAMELLIA_128_GCM_SHA256 = 49276
    TLS_DHE_RSA_WITH_CAMELLIA_256_GCM_SHA384 = 49277
    TLS_DH_RSA_WITH_CAMELLIA_128_GCM_SHA256 = 49278
    TLS_DH_RSA_WITH_CAMELLIA_256_GCM_SHA384 = 49279
    TLS_DHE_DSS_WITH_CAMELLIA_128_GCM_SHA256 = 49280
    TLS_DHE_DSS_WITH_CAMELLIA_256_GCM_SHA384 = 49281
    TLS_DH_DSS_WITH_CAMELLIA_128_GCM_SHA256 = 49282
    TLS_DH_DSS_WITH_CAMELLIA_256_GCM_SHA384 = 49283
    TLS_DH_anon_WITH_CAMELLIA_128_GCM_SHA256 = 49284
    TLS_DH_anon_WITH_CAMELLIA_256_GCM_SHA384 = 49285
    TLS_ECDHE_ECDSA_WITH_CAMELLIA_128_GCM_SHA256 = 49286
    TLS_ECDHE_ECDSA_WITH_CAMELLIA_256_GCM_SHA384 = 49287
    TLS_ECDH_ECDSA_WITH_CAMELLIA_128_GCM_SHA256 = 49288
    TLS_ECDH_ECDSA_WITH_CAMELLIA_256_GCM_SHA384 = 49289
    TLS_ECDHE_RSA_WITH_CAMELLIA_128_GCM_SHA256 = 49290
    TLS_ECDHE_RSA_WITH_CAMELLIA_256_GCM_SHA384 = 49291
    TLS_ECDH_RSA_WITH_CAMELLIA_128_GCM_SHA256 = 49292
    TLS_ECDH_RSA_WITH_CAMELLIA_256_GCM_SHA384 = 49293
    TLS_PSK_WITH_CAMELLIA_128_GCM_SHA256 = 49294
    TLS_PSK_WITH_CAMELLIA_256_GCM_SHA384 = 49295
    TLS_DHE_PSK_WITH_CAMELLIA_128_GCM_SHA256 = 49296
    TLS_DHE_PSK_WITH_CAMELLIA_256_GCM_SHA384 = 49297
    TLS_RSA_PSK_WITH_CAMELLIA_128_GCM_SHA256 = 49298
    TLS_RSA_PSK_WITH_CAMELLIA_256_GCM_SHA384 = 49299
    TLS_PSK_WITH_CAMELLIA_128_CBC_SHA256 = 49300
    TLS_PSK_WITH_CAMELLIA_256_CBC_SHA384 = 49301
    TLS_DHE_PSK_WITH_CAMELLIA_128_CBC_SHA256 = 49302
    TLS_DHE_PSK_WITH_CAMELLIA_256_CBC_SHA384 = 49303
    TLS_RSA_PSK_WITH_CAMELLIA_128_CBC_SHA256 = 49304
    TLS_RSA_PSK_WITH_CAMELLIA_256_CBC_SHA384 = 49305
    TLS_ECDHE_PSK_WITH_CAMELLIA_128_CBC_SHA256 = 49306
    TLS_ECDHE_PSK_WITH_CAMELLIA_256_CBC_SHA384 = 49307
    TLS_RSA_WITH_AES_128_CCM = 49308
    TLS_RSA_WITH_AES_256_CCM = 49309
    TLS_DHE_RSA_WITH_AES_128_CCM = 49310
    TLS_DHE_RSA_WITH_AES_256_CCM = 49311
    TLS_RSA_WITH_AES_128_CCM_8 = 49312
    TLS_RSA_WITH_AES_256_CCM_8 = 49313
    TLS_DHE_RSA_WITH_AES_128_CCM_8 = 49314
    TLS_DHE_RSA_WITH_AES_256_CCM_8 = 49315
    TLS_PSK_WITH_AES_128_CCM = 49316
    TLS_PSK_WITH_AES_256_CCM = 49317
    TLS_DHE_PSK_WITH_AES_128_CCM = 49318
    TLS_DHE_PSK_WITH_AES_256_CCM = 49319
    TLS_PSK_WITH_AES_128_CCM_8 = 49320
    TLS_PSK_WITH_AES_256_CCM_8 = 49321
    TLS_PSK_DHE_WITH_AES_128_CCM_8 = 49322
    TLS_PSK_DHE_WITH_AES_256_CCM_8 = 49323
    TLS_ECDHE_ECDSA_WITH_AES_128_CCM = 49324
    TLS_ECDHE_ECDSA_WITH_AES_256_CCM = 49325
    TLS_ECDHE_ECDSA_WITH_AES_128_CCM_8 = 49326
    TLS_ECDHE_ECDSA_WITH_AES_256_CCM_8 = 49327
    TLS_ECCPWD_WITH_AES_128_GCM_SHA256 = 49328
    TLS_ECCPWD_WITH_AES_256_GCM_SHA384 = 49329
    TLS_ECCPWD_WITH_AES_128_CCM_SHA256 = 49330
    TLS_ECCPWD_WITH_AES_256_CCM_SHA384 = 49331
    TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256 = 52392
    TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256 = 52393
    TLS_DHE_RSA_WITH_CHACHA20_POLY1305_SHA256 = 52394
    TLS_PSK_WITH_CHACHA20_POLY1305_SHA256 = 52395
    TLS_ECDHE_PSK_WITH_CHACHA20_POLY1305_SHA256 = 52396
    TLS_DHE_PSK_WITH_CHACHA20_POLY1305_SHA256 = 52397
    TLS_RSA_PSK_WITH_CHACHA20_POLY1305_SHA256 = 52398
    TLS_ECDHE_PSK_WITH_AES_128_GCM_SHA256 = 53249
    TLS_ECDHE_PSK_WITH_AES_256_GCM_SHA384 = 53250
    TLS_ECDHE_PSK_WITH_AES_128_CCM_8_SHA256 = 53251
    TLS_ECDHE_PSK_WITH_AES_128_CCM_SHA256 = 53253

# endregion
