"""this file is auto-generated by rhinocode stubmaker. do not make changes"""

# region: Exports
__all__ = ["GenericFontFamilies", "HotkeyPrefix", "TextRenderingHint", "PrivateFontCollection", "FontCollection", "InstalledFontCollection"]
# endregion

# region: Imports
from System import Drawing
from System.Runtime import CompilerServices
from typing import overload
import enum
import System
# endregion

# region: System.Drawing.Common, Version=7.0.0.0

class GenericFontFamilies(enum.Enum):
    Serif = 0
    SansSerif = 1
    Monospace = 2

class HotkeyPrefix(enum.Enum):
    None_ = 0
    Show = 1
    Hide = 2

class TextRenderingHint(enum.Enum):
    SystemDefault = 0
    SingleBitPerPixelGridFit = 1
    SingleBitPerPixel = 2
    AntiAliasGridFit = 3
    AntiAlias = 4
    ClearTypeGridFit = 5

class PrivateFontCollection(FontCollection):
    """    """
    def __init__(self): ...
    @overload
    def AddFontFile(self, filename: str) -> None: ...
    @overload
    def AddMemoryFont(self, memory: System.IntPtr, length: int) -> None: ...

class FontCollection(object):
    """    """
    @overload
    def Dispose() -> None: ...
    @property
    def Families(self) -> Drawing.System.Array[Drawing.FontFamily]: ...

class InstalledFontCollection(FontCollection):
    """    """
    def __init__(self): ...

# endregion
