"""this file is auto-generated by rhinocode stubmaker. do not make changes"""

# region: Exports
__all__ = ["GH_GenericLayout"]
# endregion

# region: Imports
from System import Drawing
from System.Collections import Generic
from System.Runtime import CompilerServices
from typing import overload
# endregion

# region: Grasshopper, Version=8.19.25132.1001

class GH_GenericLayout(object):
    """Generic layout logic for rectangle stacks.

    """
    @overload
    @staticmethod
    def Horizontal_ByIndex(area: Drawing.Rectangle, stack: Generic.List, expand: bool) -> Generic.List: ...
    @overload
    @staticmethod
    def Horizontal_ByPosition(area: Drawing.Rectangle, stack: Generic.List, expand: bool) -> Generic.List: ...
    @overload
    @staticmethod
    def Horizontal_ByPosition(area: Drawing.Rectangle, stack: Generic.List, expand: bool, radical: int) -> Generic.List: ...
    @overload
    @staticmethod
    def Vertical_ByIndex(area: Drawing.Rectangle, stack: Generic.List, expand: bool) -> Generic.List: ...
    @overload
    @staticmethod
    def Vertical_ByPosition(area: Drawing.Rectangle, stack: Generic.List, expand: bool) -> Generic.List: ...
    @overload
    @staticmethod
    def Vertical_ByPosition(area: Drawing.Rectangle, stack: Generic.List, expand: bool, radical: int) -> Generic.List: ...

# endregion
