"""this file is auto-generated by rhinocode stubmaker. do not make changes"""

# region: Exports
__all__ = ["DebugLambdaInfo", "IDebugCompilerSupport", "DebugContext"]
# endregion

# region: Imports
from System.Collections import Generic
from System.Linq import Expressions
from System.Runtime import CompilerServices
from typing import overload
# endregion

# region: Microsoft.Dynamic, Version=1.3.1.0

class DebugLambdaInfo(object):
    """    """
    def __init__(self, compilerSupport: IDebugCompilerSupport, lambdaAlias: str, optimizeForLeafFrames: bool, hiddenVariables: Generic.IList, variableAliases: Generic.IDictionary, customPayload: object): ...
    @property
    def CompilerSupport(self) -> IDebugCompilerSupport: ...
    @property
    def CustomPayload(self) -> object: ...
    @property
    def HiddenVariables(self) -> Generic.IList: ...
    @property
    def LambdaAlias(self) -> str: ...
    @property
    def OptimizeForLeafFrames(self) -> bool: ...
    @property
    def VariableAliases(self) -> Generic.IDictionary: ...

class IDebugCompilerSupport:
    """    """
    @overload
    def DoesExpressionNeedReduction(self, expression: Expressions.Expression) -> bool: ...
    @overload
    def IsCallToDebuggableLambda(self, expression: Expressions.Expression) -> bool: ...
    @overload
    def QueueExpressionForReduction(self, expression: Expressions.Expression) -> Expressions.Expression: ...

class DebugContext(object):
    """    """
    @overload
    @staticmethod
    def CreateInstance() -> DebugContext: ...
    @property
    def Mode(self) -> int: ...
    @overload
    def ResetSourceFile(self, sourceFileName: str) -> None: ...
    @overload
    def TransformLambda(self, lambda_: Expressions.LambdaExpression) -> Expressions.LambdaExpression: ...
    @overload
    def TransformLambda(self, lambda_: Expressions.LambdaExpression, lambdaInfo: DebugLambdaInfo) -> Expressions.LambdaExpression: ...

# endregion
