"""this file is auto-generated by rhinocode stubmaker. do not make changes"""

# region: Exports
__all__ = ["BinaryFormatter"]
# endregion

# region: Imports
from System.Runtime import CompilerServices
from System.Runtime import Serialization
from System.Runtime.Serialization import Formatters
from typing import overload
import System
# endregion

# region: System.Runtime.Serialization.Formatters, Version=7.0.0.0

class BinaryFormatter(object):
    """    """
    @overload
    def __init__(self): ...
    @overload
    def __init__(self, selector: Serialization.ISurrogateSelector, context: Serialization.StreamingContext): ...
    @property
    def AssemblyFormat(self) -> Formatters.FormatterAssemblyStyle: ...
    @property
    def Binder(self) -> Serialization.SerializationBinder: ...
    @property
    def Context(self) -> Serialization.StreamingContext: ...
    @property
    def FilterLevel(self) -> Formatters.TypeFilterLevel: ...
    @property
    def SurrogateSelector(self) -> Serialization.ISurrogateSelector: ...
    @property
    def TypeFormat(self) -> Formatters.FormatterTypeStyle: ...
    @AssemblyFormat.setter
    def AssemblyFormat(self, value: System.Void): ...
    @Binder.setter
    def Binder(self, value: System.Void): ...
    @Context.setter
    def Context(self, value: System.Void): ...
    @FilterLevel.setter
    def FilterLevel(self, value: System.Void): ...
    @SurrogateSelector.setter
    def SurrogateSelector(self, value: System.Void): ...
    @TypeFormat.setter
    def TypeFormat(self, value: System.Void): ...

# endregion
