"""this file is auto-generated by rhinocode stubmaker. do not make changes"""

# region: Exports
__all__ = ["Thread", "ICallback", "IHandler"]
# endregion

# region: Imports
from System.Runtime import CompilerServices
from typing import overload
import Eto
import System
# endregion

# region: Eto, Version=2.9.0.0

class Thread(Eto.Widget):
    """Provides access to platform-specific threading. Not all platforms implement this as you can use System.Threading.Thread instead in most cases.

    """
    def __init__(self, action: System.Action): ...
    @overload
    def Abort() -> None: ...
    @property
    def CurrentThread(self) -> Thread: ...
    @property
    def IsAlive(self) -> bool: ...
    @property
    def IsMain(self) -> bool: ...
    @property
    def IsMainThread(self) -> bool: ...
    @property
    def MainThread(self) -> Thread: ...
    @overload
    def Start() -> None: ...
    @property
    def StyleChanged(self): ...

class ICallback:
    """Interface for callback methods of this class

    """
    @overload
    def OnExecuted(self, widget: Thread) -> None: ...

class IHandler:
    """Handler interface for the
class

    """
    @overload
    def Abort() -> None: ...
    @overload
    def Create() -> None: ...
    @overload
    def CreateCurrent() -> None: ...
    @overload
    def CreateMain() -> None: ...
    @property
    def IsAlive(self) -> bool: ...
    @property
    def IsMain(self) -> bool: ...
    @overload
    def Start() -> None: ...

# endregion
