"""this file is auto-generated by rhinocode stubmaker. do not make changes"""

# region: Exports
__all__ = ["GH_NetworkSorter", "GH_NetworkSorterNode"]
# endregion

# region: Imports
from Grasshopper import Kernel
from System.Collections import Generic
from System.Runtime import CompilerServices
from typing import overload
import System
# endregion

# region: Grasshopper, Version=8.19.25132.1001

class GH_NetworkSorter(object):
    """    """
    def __init__(self): ...
    @overload
    def CreateContext(self, objs: Generic.List) -> None: ...
    @overload
    def CreateNodeList(self, objs: Generic.List) -> None: ...
    @overload
    def Sort(self, bDamp: System.Single, bLimit: System.Single) -> None: ...

class GH_NetworkSorterNode(object):
    """    """
    def __init__(self, obj_target: Kernel.IGH_DocumentObject): ...
    @overload
    def AdjustTarget(self, bDamp: System.Single, bLimit: System.Single) -> None: ...
    @overload
    def ConstructLinkForces() -> None: ...
    @overload
    def ConstructNodeForces(self, objs: Generic.List) -> None: ...

# endregion
