"""this file is auto-generated by rhinocode stubmaker. do not make changes"""

# region: Exports
__all__ = ["RequestCacheLevel", "RequestCachePolicy"]
# endregion

# region: Imports
from System.Runtime import CompilerServices
from typing import overload
import enum
# endregion

# region: Exports
__all__ = ["HttpCacheAgeControl", "HttpRequestCacheLevel", "HttpRequestCachePolicy"]
# endregion

# region: Imports
from System.Runtime import CompilerServices
from typing import overload
import enum
import System
# endregion

# region: System.Net.Requests, Version=7.0.0.0

class HttpCacheAgeControl(enum.Enum):
    None_ = 0
    MinFresh = 1
    MaxAge = 2
    MaxAgeAndMinFresh = 3
    MaxStale = 4
    MaxAgeAndMaxStale = 6

class HttpRequestCacheLevel(enum.Enum):
    Default = 0
    BypassCache = 1
    CacheOnly = 2
    CacheIfAvailable = 3
    Revalidate = 4
    Reload = 5
    NoCacheNoStore = 6
    CacheOrNextCacheOnly = 7
    Refresh = 8

class HttpRequestCachePolicy(RequestCachePolicy):
    """    """
    @overload
    def __init__(self): ...
    @overload
    def __init__(self, level: HttpRequestCacheLevel): ...
    @overload
    def __init__(self, cacheSyncDate: System.DateTime): ...
    @overload
    def __init__(self, cacheAgeControl: HttpCacheAgeControl, ageOrFreshOrStale: System.TimeSpan): ...
    @overload
    def __init__(self, cacheAgeControl: HttpCacheAgeControl, maxAge: System.TimeSpan, freshOrStale: System.TimeSpan): ...
    @overload
    def __init__(self, cacheAgeControl: HttpCacheAgeControl, maxAge: System.TimeSpan, freshOrStale: System.TimeSpan, cacheSyncDate: System.DateTime): ...
    @property
    def CacheSyncDate(self) -> System.DateTime: ...
    @property
    def Level(self) -> HttpRequestCacheLevel: ...
    @property
    def MaxAge(self) -> System.TimeSpan: ...
    @property
    def MaxStale(self) -> System.TimeSpan: ...
    @property
    def MinFresh(self) -> System.TimeSpan: ...
    @overload
    def ToString() -> str: ...

# endregion

# region: System.Net.Primitives, Version=7.0.0.0

class RequestCacheLevel(enum.Enum):
    Default = 0
    BypassCache = 1
    CacheOnly = 2
    CacheIfAvailable = 3
    Revalidate = 4
    Reload = 5
    NoCacheNoStore = 6

class RequestCachePolicy(object):
    """    """
    @overload
    def __init__(self): ...
    @overload
    def __init__(self, level: RequestCacheLevel): ...
    @property
    def Level(self) -> RequestCacheLevel: ...
    @overload
    def ToString() -> str: ...

# endregion
