"""this file is auto-generated by rhinocode stubmaker. do not make changes"""

# region: Exports
__all__ = ["X509IssuerSerial"]
# endregion

# region: Imports
from System.Runtime import CompilerServices
from typing import overload
import System
# endregion

# region: System.Security.Cryptography.Pkcs, Version=7.0.0.0

class X509IssuerSerial(System.ValueType):
    """    """
    @property
    def IssuerName(self) -> str: ...
    @property
    def SerialNumber(self) -> str: ...
    @IssuerName.setter
    def IssuerName(self, value: System.Void): ...
    @SerialNumber.setter
    def SerialNumber(self, value: System.Void): ...

# endregion
