"""this file is auto-generated by rhinocode stubmaker. do not make changes"""

# region: Exports
__all__ = ["XamlAccessLevel"]
# endregion

# region: Imports
from System import Reflection
from System.Runtime import CompilerServices
from typing import overload
import System
# endregion

# region: Exports
__all__ = []
# endregion

# region: Imports
from System.Runtime import CompilerServices
from typing import overload
# endregion

# region: System.Security.Permissions, Version=7.0.0.0

# endregion

# region: System.Windows.Extensions, Version=7.0.0.0

class XamlAccessLevel(object):
    """    """
    @overload
    @staticmethod
    def AssemblyAccessTo(assembly: Reflection.Assembly) -> XamlAccessLevel: ...
    @overload
    @staticmethod
    def AssemblyAccessTo(assemblyName: Reflection.AssemblyName) -> XamlAccessLevel: ...
    @property
    def AssemblyAccessToAssemblyName(self) -> Reflection.AssemblyName: ...
    @property
    def PrivateAccessToTypeName(self) -> str: ...
    @overload
    @staticmethod
    def PrivateAccessTo(type_: System.Type) -> XamlAccessLevel: ...
    @overload
    @staticmethod
    def PrivateAccessTo(assemblyQualifiedTypeName: str) -> XamlAccessLevel: ...

# endregion
