"""this file is auto-generated by rhinocode stubmaker. do not make changes"""

# region: Exports
__all__ = ["Runtime", "Console", "Error"]
# endregion

# region: Imports
from System.Runtime import CompilerServices
from typing import overload
# endregion

# region: System.Private.CoreLib, Version=7.0.0.0

class Console(object):
    """    """
    @overload
    @staticmethod
    def Write(s: str) -> None: ...
    @overload
    @staticmethod
    def WriteLine() -> None: ...
    @overload
    @staticmethod
    def WriteLine(s: str) -> None: ...

class Error(object):
    """    """
    @overload
    @staticmethod
    def Write(s: str) -> None: ...

# endregion
