"""this file is auto-generated by rhinocode stubmaker. do not make changes"""

# region: Exports
__all__ = ["AssemblyHashAlgorithm", "AssemblyVersionCompatibility"]
# endregion

# region: Imports
from System.Runtime import CompilerServices
from typing import overload
import enum
# endregion

# region: System.Private.CoreLib, Version=7.0.0.0

class AssemblyHashAlgorithm(enum.Enum):
    None_ = 0
    MD5 = 32771
    SHA1 = 32772
    SHA256 = 32780
    SHA384 = 32781
    SHA512 = 32782

class AssemblyVersionCompatibility(enum.Enum):
    SameMachine = 1
    SameProcess = 2
    SameDomain = 3

# endregion
