"""this file is auto-generated by rhinocode stubmaker. do not make changes"""

# region: Exports
__all__ = []
# endregion

# region: Imports
from System.Runtime import CompilerServices
from typing import overload
# endregion

# region: RhinoCommon, Version=8.19.25132.1001

# endregion
