"""this file is auto-generated by rhinocode stubmaker. do not make changes"""

# region: Exports
__all__ = ["Grasshopper1DebugGroup", "Grasshopper1ProfileGroup", "Grasshopper1RunGroup"]
# endregion

# region: Imports
from Rhino.Runtime import Code
from Rhino.Runtime.Code import Execution
from Rhino.Runtime.Code.Execution import Debugging
from Rhino.Runtime.Code.Execution import Profiling
from RhinoCodePlatform.Rhino3D.Languages.GH1 import Legacy
from System.Runtime import CompilerServices
from typing import overload
# endregion

# region: RhinoCodePlatform.Rhino3D, Version=8.19.25132.1001

class Grasshopper1DebugGroup(Debugging.DebugGroup):
    """    """
    @overload
    def __init__(self, code: Code.Code, proxy: Legacy.ProxyDocument): ...
    @overload
    def __init__(self, code: Code.Code, context: Debugging.DebugContext, proxy: Legacy.ProxyDocument): ...
    @property
    def ProxyDocument(self) -> Legacy.ProxyDocument: ...

class Grasshopper1ProfileGroup(Profiling.ProfileGroup):
    """    """
    @overload
    def __init__(self, code: Code.Code, proxy: Legacy.ProxyDocument): ...
    @overload
    def __init__(self, code: Code.Code, context: Profiling.ProfileContext, proxy: Legacy.ProxyDocument): ...
    @property
    def ProxyDocument(self) -> Legacy.ProxyDocument: ...

class Grasshopper1RunGroup(Execution.RunGroup):
    """    """
    @overload
    def __init__(self, code: Code.Code, proxy: Legacy.ProxyDocument): ...
    @overload
    def __init__(self, code: Code.Code, context: Execution.RunContext, proxy: Legacy.ProxyDocument): ...
    @property
    def ProxyDocument(self) -> Legacy.ProxyDocument: ...

# endregion
