"""this file is auto-generated by rhinocode stubmaker. do not make changes"""

# region: Exports
__all__ = ["ICommand"]
# endregion

# region: Imports
from System.Runtime import CompilerServices
from typing import overload
import System
# endregion

# region: System.ObjectModel, Version=7.0.0.0

class ICommand:
    """    """
    @overload
    def CanExecute(self, parameter: object) -> bool: ...
    @overload
    def Execute(self, parameter: object) -> None: ...
    @property
    def CanExecuteChanged(self): ...

# endregion
