"""this file is auto-generated by rhinocode stubmaker. do not make changes"""

# region: Exports
__all__ = ["Binder", "CSharpArgumentInfo", "CSharpArgumentInfoFlags", "CSharpBinderFlags", "RuntimeBinderException", "RuntimeBinderInternalCompilerException"]
# endregion

# region: Imports
from System.Collections import Generic
from System.Linq import Expressions
from System.Runtime import CompilerServices
from typing import overload
import enum
import System
# endregion

# region: Microsoft.CSharp, Version=7.0.0.0

class Binder(object):
    """    """
    @overload
    @staticmethod
    def BinaryOperation(flags: CSharpBinderFlags, operation: Expressions.ExpressionType, context: System.Type, argumentInfo: Generic.IEnumerable) -> CompilerServices.CallSiteBinder: ...
    @overload
    @staticmethod
    def Convert(flags: CSharpBinderFlags, type_: System.Type, context: System.Type) -> CompilerServices.CallSiteBinder: ...
    @overload
    @staticmethod
    def GetIndex(flags: CSharpBinderFlags, context: System.Type, argumentInfo: Generic.IEnumerable) -> CompilerServices.CallSiteBinder: ...
    @overload
    @staticmethod
    def GetMember(flags: CSharpBinderFlags, name: str, context: System.Type, argumentInfo: Generic.IEnumerable) -> CompilerServices.CallSiteBinder: ...
    @overload
    @staticmethod
    def Invoke(flags: CSharpBinderFlags, context: System.Type, argumentInfo: Generic.IEnumerable) -> CompilerServices.CallSiteBinder: ...
    @overload
    @staticmethod
    def InvokeConstructor(flags: CSharpBinderFlags, context: System.Type, argumentInfo: Generic.IEnumerable) -> CompilerServices.CallSiteBinder: ...
    @overload
    @staticmethod
    def InvokeMember(flags: CSharpBinderFlags, name: str, typeArguments: Generic.IEnumerable, context: System.Type, argumentInfo: Generic.IEnumerable) -> CompilerServices.CallSiteBinder: ...
    @overload
    @staticmethod
    def IsEvent(flags: CSharpBinderFlags, name: str, context: System.Type) -> CompilerServices.CallSiteBinder: ...
    @overload
    @staticmethod
    def SetIndex(flags: CSharpBinderFlags, context: System.Type, argumentInfo: Generic.IEnumerable) -> CompilerServices.CallSiteBinder: ...
    @overload
    @staticmethod
    def SetMember(flags: CSharpBinderFlags, name: str, context: System.Type, argumentInfo: Generic.IEnumerable) -> CompilerServices.CallSiteBinder: ...
    @overload
    @staticmethod
    def UnaryOperation(flags: CSharpBinderFlags, operation: Expressions.ExpressionType, context: System.Type, argumentInfo: Generic.IEnumerable) -> CompilerServices.CallSiteBinder: ...

class CSharpArgumentInfo(object):
    """    """
    @overload
    @staticmethod
    def Create(flags: CSharpArgumentInfoFlags, name: str) -> CSharpArgumentInfo: ...

class CSharpArgumentInfoFlags(enum.Enum):
    None_ = 0
    UseCompileTimeType = 1
    Constant = 2
    NamedArgument = 4
    IsRef = 8
    IsOut = 16
    IsStaticType = 32

class CSharpBinderFlags(enum.Enum):
    None_ = 0
    CheckedContext = 1
    InvokeSimpleName = 2
    InvokeSpecialName = 4
    BinaryOperationLogical = 8
    ConvertExplicit = 16
    ConvertArrayIndex = 32
    ResultIndexed = 64
    ValueFromCompoundAssignment = 128
    ResultDiscarded = 256

class RuntimeBinderException(System.Exception):
    """    """
    @overload
    def __init__(self): ...
    @overload
    def __init__(self, message: str): ...
    @overload
    def __init__(self, message: str, innerException: System.Exception): ...

class RuntimeBinderInternalCompilerException(System.Exception):
    """    """
    @overload
    def __init__(self): ...
    @overload
    def __init__(self, message: str): ...
    @overload
    def __init__(self, message: str, innerException: System.Exception): ...

# endregion
