"""this file is auto-generated by rhinocode stubmaker. do not make changes"""

# region: Exports
__all__ = ["Grasshopper1ContextIdentity"]
# endregion

# region: Imports
from Rhino.Runtime.Code import Execution
from System.Runtime import CompilerServices
from typing import overload
# endregion

# region: RhinoCodePlatform.Rhino3D, Version=8.19.25132.1001

class Grasshopper1ContextIdentity(Execution.ContextIdentity):
    """    """
    @overload
    def __init__(self): ...
    @overload
    def __init__(self, name: str, index: int): ...
    @overload
    def __init__(self, index: int, iterations: int): ...
    @overload
    def CompareTo(self, other: Execution.ContextIdentity) -> int: ...
    @property
    def Index(self) -> int: ...

# endregion
