"""this file is auto-generated by rhinocode stubmaker. do not make changes"""

# region: Exports
__all__ = ["GH_GDLParser"]
# endregion

# region: Imports
from Grasshopper import Kernel
from System.Runtime import CompilerServices
from typing import overload
import System
# endregion

# region: Grasshopper, Version=8.19.25132.1001

class GH_GDLParser(object):
    """Provided functionality for parsing and writing Grasshopper Descriptor Language text.

    """
    @overload
    @staticmethod
    def ParseGDL(lines: System.System.Array[str]) -> (Kernel.GH_Document, System.System.Array[str]): ...

# endregion
