"""this file is auto-generated by rhinocode stubmaker. do not make changes"""

# region: Exports
__all__ = ["ControlBarResizeMode"]
# endregion

# region: Imports
from System.Runtime import CompilerServices
from typing import overload
import enum
# endregion

# region: Rhino.UI, Version=8.19.25132.1001

class ControlBarResizeMode(enum.Enum):
    Left = 10
    Right = 11
    Top = 12
    TopLeft = 13
    TopRight = 14
    Bottom = 15
    BottomLeft = 16
    BottomRight = 17

# endregion
