"""this file is auto-generated by rhinocode stubmaker. do not make changes"""

# region: Exports
__all__ = ["AutomationLiveSetting", "AutomationNotificationKind", "AutomationNotificationProcessing", "IAutomationLiveRegion"]
# endregion

# region: Imports
from System.Runtime import CompilerServices
from typing import overload
import enum
import System
# endregion

# region: System.Windows.Forms.Primitives, Version=7.0.0.0

class AutomationLiveSetting(enum.Enum):
    Off = 0
    Polite = 1
    Assertive = 2

class AutomationNotificationKind(enum.Enum):
    ItemAdded = 0
    ItemRemoved = 1
    ActionCompleted = 2
    ActionAborted = 3
    Other = 4

class AutomationNotificationProcessing(enum.Enum):
    ImportantAll = 0
    ImportantMostRecent = 1
    All = 2
    MostRecent = 3
    CurrentThenMostRecent = 4

class IAutomationLiveRegion:
    """    """
    @property
    def LiveSetting(self) -> AutomationLiveSetting: ...
    @LiveSetting.setter
    def LiveSetting(self, value: System.Void): ...

# endregion
