"""this file is auto-generated by rhinocode stubmaker. do not make changes"""

# region: Exports
__all__ = ["IGradient"]
# endregion

# region: Imports
from Rhino import Display
from System import Drawing
from System.Collections import Generic
from System.Runtime import CompilerServices
from typing import overload
import System
# endregion

# region: Rhino.UI, Version=8.19.25132.1001

class IGradient:
    """    """
    @overload
    def Draw(self, graphics: Drawing.Graphics, dest: Drawing.RectangleF) -> None: ...
    @overload
    def GetColorStops() -> Display.System.Array[Display.ColorStop]: ...
    @overload
    def MouseDown(self, dest: Drawing.RectangleF, point: Drawing.PointF) -> bool: ...
    @overload
    def MouseMove(self, dest: Drawing.RectangleF, point: Drawing.PointF) -> bool: ...
    @overload
    def MouseUp(self, dest: Drawing.RectangleF, point: Drawing.PointF, deselect: bool) -> bool: ...
    @overload
    def SetColorStops(self, stops: Generic.IEnumerable) -> None: ...
    @property
    def GradientChanged(self): ...
    @property
    def SelectionChanged(self): ...

# endregion
