"""this file is auto-generated by rhinocode stubmaker. do not make changes"""

# region: Exports
__all__ = ["ObjectHandle"]
# endregion

# region: Imports
from System.Runtime import CompilerServices
from typing import overload
import System
# endregion

# region: System.Private.CoreLib, Version=7.0.0.0

class ObjectHandle(System.MarshalByRefObject):
    """    """
    def __init__(self, o: object): ...
    @overload
    def Unwrap() -> object: ...

# endregion
