"""this file is auto-generated by rhinocode stubmaker. do not make changes"""

# region: Exports
__all__ = ["ServiceControllerPermissionAccess", "ServiceControllerPermissionEntry", "ServiceControllerPermissionEntryCollection"]
# endregion

# region: Imports
from System import Collections
from System.Runtime import CompilerServices
from typing import overload
import enum
import System
# endregion

# region: System.Security.Permissions, Version=7.0.0.0

class ServiceControllerPermissionAccess(enum.Enum):
    None_ = 0
    Browse = 2
    Control = 6

class ServiceControllerPermissionEntry(object):
    """    """
    @overload
    def __init__(self): ...
    @overload
    def __init__(self, permissionAccess: ServiceControllerPermissionAccess, machineName: str, serviceName: str): ...
    @property
    def MachineName(self) -> str: ...
    @property
    def PermissionAccess(self) -> ServiceControllerPermissionAccess: ...
    @property
    def ServiceName(self) -> str: ...

class ServiceControllerPermissionEntryCollection(Collections.CollectionBase):
    """    """
    @overload
    def Add(self, value: ServiceControllerPermissionEntry) -> int: ...
    @overload
    def AddRange(self, value: System.Array[ServiceControllerPermissionEntry]) -> None: ...
    @overload
    def AddRange(self, value: ServiceControllerPermissionEntryCollection) -> None: ...
    @overload
    def Contains(self, value: ServiceControllerPermissionEntry) -> bool: ...
    @overload
    def CopyTo(self, array: System.Array[ServiceControllerPermissionEntry], index: int) -> None: ...
    @property
    def Item(self) -> ServiceControllerPermissionEntry: ...
    @overload
    def IndexOf(self, value: ServiceControllerPermissionEntry) -> int: ...
    @overload
    def Insert(self, index: int, value: ServiceControllerPermissionEntry) -> None: ...
    @overload
    def Remove(self, value: ServiceControllerPermissionEntry) -> None: ...
    @Item.setter
    def Item(self, value: System.Void): ...

# endregion
