"""this file is auto-generated by rhinocode stubmaker. do not make changes"""

# region: Exports
__all__ = ["IPreviewCommand", "IPreviewCommandSource"]
# endregion

# region: Imports
from System.Runtime import CompilerServices
from typing import overload
# endregion

# region: System.Windows.Controls.Ribbon, Version=7.0.0.0

class IPreviewCommand:
    """    """
    @overload
    def CancelPreview() -> None: ...
    @overload
    def Preview(self, parameter: object) -> None: ...

class IPreviewCommandSource:
    """    """
    @property
    def PreviewCommandParameter(self) -> object: ...

# endregion
