"""this file is auto-generated by rhinocode stubmaker. do not make changes"""

# region: Exports
__all__ = ["RibbonApplicationMenuAutomationPeer", "RibbonButtonAutomationPeer", "RibbonCheckBoxAutomationPeer", "RibbonControlAutomationPeer", "RibbonControlDataAutomationPeer", "RibbonControlGroupAutomationPeer", "RibbonRadioButtonAutomationPeer", "RibbonTextBoxAutomationPeer", "RibbonToggleButtonAutomationPeer", "RibbonToolTipAutomationPeer", "RibbonAutomationPeer", "RibbonComboBoxAutomationPeer", "RibbonContextMenuAutomationPeer", "RibbonContextualTabGroupAutomationPeer", "RibbonContextualTabGroupDataAutomationPeer", "RibbonContextualTabGroupItemsControlAutomationPeer", "RibbonGalleryAutomationPeer", "RibbonGalleryCategoryAutomationPeer", "RibbonGalleryCategoryDataAutomationPeer", "RibbonGalleryItemAutomationPeer", "RibbonGalleryItemDataAutomationPeer", "RibbonGroupAutomationPeer", "RibbonGroupDataAutomationPeer", "RibbonGroupHeaderAutomationPeer", "RibbonMenuButtonAutomationPeer", "RibbonMenuItemDataAutomationPeer", "RibbonMenuItemAutomationPeer", "RibbonQuickAccessToolBarAutomationPeer", "RibbonSeparatorAutomationPeer", "RibbonSplitButtonAutomationPeer", "RibbonTabAutomationPeer", "RibbonTabDataAutomationPeer", "RibbonTabHeaderAutomationPeer", "RibbonTabHeaderDataAutomationPeer", "RibbonTabHeaderItemsControlAutomationPeer", "RibbonTitleAutomationPeer", "RibbonTwoLineTextAutomationPeer"]
# endregion

# region: Imports
from System import Windows
from System.Runtime import CompilerServices
from System.Windows import Automation
from System.Windows.Controls import Ribbon
from typing import overload
# endregion

# region: System.Windows.Controls.Ribbon, Version=7.0.0.0

class RibbonApplicationMenuAutomationPeer(RibbonMenuButtonAutomationPeer):
    """    """
    def __init__(self, owner: Ribbon.RibbonApplicationMenu): ...

class RibbonButtonAutomationPeer(ButtonAutomationPeer):
    """    """
    def __init__(self, owner: Ribbon.RibbonButton): ...

class RibbonCheckBoxAutomationPeer(CheckBoxAutomationPeer):
    """    """
    def __init__(self, owner: Ribbon.RibbonCheckBox): ...

class RibbonControlAutomationPeer(FrameworkElementAutomationPeer):
    """    """
    def __init__(self, owner: Windows.FrameworkElement): ...

class RibbonControlDataAutomationPeer(ItemAutomationPeer):
    """    """
    def __init__(self, item: object, itemsControlPeer: ItemsControlAutomationPeer): ...
    @overload
    def GetPattern(self, patternInterface: PatternInterface) -> object: ...

class RibbonControlGroupAutomationPeer(ItemsControlAutomationPeer):
    """    """
    def __init__(self, owner: Ribbon.RibbonControlGroup): ...

class RibbonRadioButtonAutomationPeer(RadioButtonAutomationPeer):
    """    """
    def __init__(self, owner: Ribbon.RibbonRadioButton): ...

class RibbonTextBoxAutomationPeer(TextBoxAutomationPeer):
    """    """
    def __init__(self, owner: Ribbon.RibbonTextBox): ...
    @overload
    def GetPattern(self, patternInterface: PatternInterface) -> object: ...

class RibbonToggleButtonAutomationPeer(ToggleButtonAutomationPeer):
    """    """
    def __init__(self, owner: Ribbon.RibbonToggleButton): ...

class RibbonToolTipAutomationPeer(ToolTipAutomationPeer):
    """    """
    def __init__(self, owner: Ribbon.RibbonToolTip): ...

class RibbonAutomationPeer(SelectorAutomationPeer):
    """    """
    def __init__(self, owner: Ribbon.Ribbon): ...
    @overload
    def Collapse() -> None: ...
    @overload
    def Expand() -> None: ...
    @property
    def ExpandCollapseState(self) -> Automation.ExpandCollapseState: ...
    @overload
    def GetPattern(self, patternInterface: PatternInterface) -> object: ...

class RibbonComboBoxAutomationPeer(RibbonMenuButtonAutomationPeer):
    """    """
    def __init__(self, owner: Ribbon.RibbonComboBox): ...
    @property
    def IsReadOnly(self) -> bool: ...
    @property
    def Value(self) -> str: ...
    @overload
    def GetPattern(self, patternInterface: PatternInterface) -> object: ...
    @overload
    def SetValue(self, value: str) -> None: ...

class RibbonContextMenuAutomationPeer(ItemsControlAutomationPeer):
    """    """
    def __init__(self, owner: Ribbon.RibbonContextMenu): ...

class RibbonContextualTabGroupAutomationPeer(FrameworkElementAutomationPeer):
    """    """
    def __init__(self, owner: Ribbon.RibbonContextualTabGroup): ...

class RibbonContextualTabGroupDataAutomationPeer(ItemAutomationPeer):
    """    """
    def __init__(self, item: object, owner: RibbonContextualTabGroupItemsControlAutomationPeer): ...
    @overload
    def GetPattern(self, patternInterface: PatternInterface) -> object: ...

class RibbonContextualTabGroupItemsControlAutomationPeer(ItemsControlAutomationPeer):
    """    """
    def __init__(self, owner: Ribbon.RibbonContextualTabGroupItemsControl): ...
    @overload
    def GetPattern(self, patternInterface: PatternInterface) -> object: ...

class RibbonGalleryAutomationPeer(ItemsControlAutomationPeer):
    """    """
    def __init__(self, owner: Ribbon.RibbonGallery): ...
    @overload
    def GetPattern(self, patternInterface: PatternInterface) -> object: ...

class RibbonGalleryCategoryAutomationPeer(ItemsControlAutomationPeer):
    """    """
    def __init__(self, owner: Ribbon.RibbonGalleryCategory): ...
    @overload
    def GetPattern(self, patternInterface: PatternInterface) -> object: ...

class RibbonGalleryCategoryDataAutomationPeer(ItemAutomationPeer):
    """    """
    def __init__(self, owner: object, itemsControlAutomationPeer: ItemsControlAutomationPeer): ...
    @overload
    def GetPattern(self, patternInterface: PatternInterface) -> object: ...

class RibbonGalleryItemAutomationPeer(FrameworkElementAutomationPeer):
    """    """
    def __init__(self, owner: Ribbon.RibbonGalleryItem): ...

class RibbonGalleryItemDataAutomationPeer(ItemAutomationPeer):
    """    """
    def __init__(self, owner: object, itemsControlAutomationPeer: ItemsControlAutomationPeer, parentCategoryDataAutomationPeer: RibbonGalleryCategoryDataAutomationPeer): ...
    @property
    def ParentCategoryDataAutomationPeer(self) -> RibbonGalleryCategoryDataAutomationPeer: ...
    @overload
    def GetPattern(self, patternInterface: PatternInterface) -> object: ...

class RibbonGroupAutomationPeer(ItemsControlAutomationPeer):
    """    """
    def __init__(self, owner: Ribbon.RibbonGroup): ...
    @overload
    def GetPattern(self, patternInterface: PatternInterface) -> object: ...

class RibbonGroupDataAutomationPeer(ItemAutomationPeer):
    """    """
    def __init__(self, item: object, itemsControlPeer: RibbonTabAutomationPeer): ...
    @overload
    def GetPattern(self, patternInterface: PatternInterface) -> object: ...

class RibbonGroupHeaderAutomationPeer(FrameworkElementAutomationPeer):
    """    """
    def __init__(self, owner: Windows.FrameworkElement): ...

class RibbonMenuButtonAutomationPeer(ItemsControlAutomationPeer):
    """    """
    def __init__(self, owner: Ribbon.RibbonMenuButton): ...
    @overload
    def GetPattern(self, patternInterface: PatternInterface) -> object: ...

class RibbonMenuItemDataAutomationPeer(ItemAutomationPeer):
    """    """
    def __init__(self, item: object, itemsControlPeer: ItemsControlAutomationPeer): ...
    @overload
    def GetPattern(self, patternInterface: PatternInterface) -> object: ...

class RibbonMenuItemAutomationPeer(ItemsControlAutomationPeer):
    """    """
    def __init__(self, owner: Ribbon.RibbonMenuItem): ...

class RibbonQuickAccessToolBarAutomationPeer(ItemsControlAutomationPeer):
    """    """
    def __init__(self, owner: Ribbon.RibbonQuickAccessToolBar): ...
    @overload
    def Collapse() -> None: ...
    @overload
    def Expand() -> None: ...
    @property
    def ExpandCollapseState(self) -> Automation.ExpandCollapseState: ...
    @overload
    def GetPattern(self, patternInterface: PatternInterface) -> object: ...

class RibbonSeparatorAutomationPeer(SeparatorAutomationPeer):
    """    """
    def __init__(self, owner: Ribbon.RibbonSeparator): ...

class RibbonSplitButtonAutomationPeer(RibbonMenuButtonAutomationPeer):
    """    """
    def __init__(self, owner: Ribbon.RibbonSplitButton): ...
    @overload
    def GetPattern(self, patternInterface: PatternInterface) -> object: ...

class RibbonTabAutomationPeer(ItemsControlAutomationPeer):
    """    """
    def __init__(self, owner: Ribbon.RibbonTab): ...

class RibbonTabDataAutomationPeer(SelectorItemAutomationPeer):
    """    """
    def __init__(self, item: object, itemsControlPeer: RibbonAutomationPeer): ...
    @overload
    def GetPattern(self, patternInterface: PatternInterface) -> object: ...

class RibbonTabHeaderAutomationPeer(FrameworkElementAutomationPeer):
    """    """
    def __init__(self, owner: Ribbon.RibbonTabHeader): ...

class RibbonTabHeaderDataAutomationPeer(ItemAutomationPeer):
    """    """
    def __init__(self, item: object, itemsControlPeer: RibbonTabHeaderItemsControlAutomationPeer): ...
    @overload
    def GetPattern(self, patternInterface: PatternInterface) -> object: ...

class RibbonTabHeaderItemsControlAutomationPeer(ItemsControlAutomationPeer):
    """    """
    def __init__(self, owner: Ribbon.RibbonTabHeaderItemsControl): ...

class RibbonTitleAutomationPeer(FrameworkElementAutomationPeer):
    """    """
    def __init__(self, owner: Windows.FrameworkElement): ...

class RibbonTwoLineTextAutomationPeer(FrameworkElementAutomationPeer):
    """    """
    def __init__(self, owner: Ribbon.RibbonTwoLineText): ...

# endregion
