"""this file is auto-generated by rhinocode stubmaker. do not make changes"""

# region: Exports
__all__ = ["Collaboration", "PnrpScope"]
# endregion

# region: Imports
from System.Runtime import CompilerServices
from typing import overload
import enum
# endregion

# region: System.Security.Permissions, Version=7.0.0.0

class PnrpScope(enum.Enum):
    All = 0
    Global = 1
    SiteLocal = 2
    LinkLocal = 3

# endregion
