"""this file is auto-generated by rhinocode stubmaker. do not make changes"""

# region: Exports
__all__ = ["Rhino3DServer"]
# endregion

# region: Imports
from Rhino.Runtime.Code import Platform
from Rhino.Runtime.Code.Remote import Server
from System.Runtime import CompilerServices
from typing import overload
# endregion

# region: RhinoCodePlatform.Rhino3D, Version=8.19.25132.1001

class Rhino3DServer(Server.PipeServer):
    """    """
    def __init__(self, platform: Platform.IPlatform): ...

# endregion
