"""this file is auto-generated by rhinocode stubmaker. do not make changes"""

# region: Exports
__all__ = ["IRootGridEntry", "PropertiesTab", "PropertyGridCommands"]
# endregion

# region: Imports
from System import ComponentModel
from System.ComponentModel import Design
from System.Runtime import CompilerServices
from System.Windows.Forms import Design
from typing import overload
import System
# endregion

# region: System.Windows.Forms, Version=7.0.0.0

class IRootGridEntry:
    """    """
    @property
    def BrowsableAttributes(self) -> ComponentModel.AttributeCollection: ...
    @overload
    def ResetBrowsableAttributes() -> None: ...
    @BrowsableAttributes.setter
    def BrowsableAttributes(self, value: System.Void): ...
    @overload
    def ShowCategories(self, showCategories: bool) -> None: ...

class PropertiesTab(Design.PropertyTab):
    """    """
    def __init__(self): ...
    @property
    def HelpKeyword(self) -> str: ...
    @property
    def TabName(self) -> str: ...
    @overload
    def GetDefaultProperty(self, obj: object) -> ComponentModel.PropertyDescriptor: ...
    @overload
    def GetProperties(self, component: object, attributes: System.System.Array[System.Attribute]) -> ComponentModel.PropertyDescriptorCollection: ...
    @overload
    def GetProperties(self, context: ComponentModel.ITypeDescriptorContext, component: object, attributes: System.System.Array[System.Attribute]) -> ComponentModel.PropertyDescriptorCollection: ...

class PropertyGridCommands(object):
    """    """
    def __init__(self): ...
    @property
    def Reset(self) -> Design.CommandID: ...
    @property
    def Description(self) -> Design.CommandID: ...
    @property
    def Hide(self) -> Design.CommandID: ...
    @property
    def Commands(self) -> Design.CommandID: ...

# endregion
