"""this file is auto-generated by rhinocode stubmaker. do not make changes"""

# region: Exports
__all__ = ["TetherDestroyedEventHandler", "TetherDestroyedEventArgs", "CurveTetherStyle"]
# endregion

# region: Imports
from System.Runtime import CompilerServices
from typing import overload
import enum
import System
# endregion

# region: Rhino.UI, Version=8.19.25132.1001

class TetherDestroyedEventHandler(System.MulticastDelegate):
    """    """
    def __init__(self, object_: object, method: System.IntPtr): ...
    @overload
    def BeginInvoke(self, source: object, e: TetherDestroyedEventArgs, callback: System.AsyncCallback, object_: object) -> System.IAsyncResult: ...
    @overload
    def EndInvoke(self, result: System.IAsyncResult) -> None: ...
    @overload
    def Invoke(self, source: object, e: TetherDestroyedEventArgs) -> None: ...

class TetherDestroyedEventArgs(System.EventArgs):
    """    """
    def __init__(self): ...

class CurveTetherStyle(enum.Enum):
    ScreenTangent = 1
    WorldTangent = 2
    ScreenPerpendicular = 3
    MaximumCurvature = 4

# endregion
