"""this file is auto-generated by rhinocode stubmaker. do not make changes"""

# region: Exports
__all__ = ["HostingHelpers"]
# endregion

# region: Imports
from Microsoft import Scripting
from Microsoft.Scripting import Hosting
from Microsoft.Scripting import Runtime
from System.Runtime import CompilerServices
from typing import overload
# endregion

# region: Microsoft.Scripting, Version=1.3.1.0

class HostingHelpers(object):
    """    """
    @overload
    @staticmethod
    def CreateDocumentationOperations(provider: Runtime.DocumentationProvider) -> Hosting.DocumentationOperations: ...
    @overload
    @staticmethod
    def CreateScriptScope(engine: Hosting.ScriptEngine, scope: Runtime.Scope) -> Hosting.ScriptScope: ...
    @overload
    @staticmethod
    def GetDomainManager(runtime: Hosting.ScriptRuntime) -> Runtime.ScriptDomainManager: ...
    @overload
    @staticmethod
    def GetLanguageContext(engine: Hosting.ScriptEngine) -> Runtime.LanguageContext: ...
    @overload
    @staticmethod
    def GetScope(scriptScope: Hosting.ScriptScope) -> Runtime.Scope: ...
    @overload
    @staticmethod
    def GetScriptCode(compiledCode: Hosting.CompiledCode) -> Scripting.ScriptCode: ...
    @overload
    @staticmethod
    def GetSharedIO(io: Hosting.ScriptIO) -> Runtime.SharedIO: ...
    @overload
    @staticmethod
    def GetSourceUnit(scriptSource: Hosting.ScriptSource) -> Scripting.SourceUnit: ...

# endregion
