"""this file is auto-generated by rhinocode stubmaker. do not make changes"""

# region: Exports
__all__ = ["Binary", "FormatterTypeStyle", "FormatterAssemblyStyle", "TypeFilterLevel", "IFieldInfo"]
# endregion

# region: Imports
from System.Runtime import CompilerServices
from typing import overload
import enum
import System
# endregion

# region: System.Runtime.Serialization.Formatters, Version=7.0.0.0

class FormatterTypeStyle(enum.Enum):
    TypesWhenNeeded = 0
    TypesAlways = 1
    XsdString = 2

class FormatterAssemblyStyle(enum.Enum):
    Simple = 0
    Full = 1

class TypeFilterLevel(enum.Enum):
    Low = 2
    Full = 3

class IFieldInfo:
    """    """
    @property
    def FieldNames(self) -> System.System.Array[str]: ...
    @property
    def FieldTypes(self) -> System.System.Array[System.Type]: ...
    @FieldNames.setter
    def FieldNames(self, value: System.Void): ...
    @FieldTypes.setter
    def FieldTypes(self, value: System.Void): ...

# endregion
