"""this file is auto-generated by rhinocode stubmaker. do not make changes"""

# region: Exports
__all__ = ["IGH_TagArtist", "GH_TagArtist", "GH_TagArtist_WirePainter"]
# endregion

# region: Imports
from Grasshopper import Kernel
from Grasshopper.GUI import Canvas
from System import Drawing
from System.Runtime import CompilerServices
from typing import overload
import System
# endregion

# region: Grasshopper, Version=8.19.25132.1001

class IGH_TagArtist:
    """Defines the interface for TagArtist objects. TagArtists can be used to paint additional stuff onto a GH_Canvas.

    """
    @property
    def ID(self) -> System.Guid: ...
    @overload
    def Paint(self, canvas: Canvas.GH_Canvas, channel: Canvas.GH_CanvasChannel) -> None: ...

class GH_TagArtist(object):
    """Provides a basic implementation of the IGH_TagArtist interface.

    """
    @property
    def ID(self) -> System.Guid: ...
    @overload
    def Paint(self, canvas: Canvas.GH_Canvas, channel: Canvas.GH_CanvasChannel) -> None: ...

class GH_TagArtist_WirePainter(GH_TagArtist):
    """IGH_TagArtist implementation for drawing individual wires.

    """
    def __init__(self, source: Kernel.IGH_Param, target: Kernel.IGH_Param, colour: Drawing.Color, width: int): ...
    @property
    def WirePainter_ID(self) -> System.Guid: ...
    @overload
    def Paint(self, canvas: Canvas.GH_Canvas, channel: Canvas.GH_CanvasChannel) -> None: ...

# endregion
